### ISSUE TITLE
Integrate codegen.apinf.io with APInf as one of the service for developers

### ISSUE THREAD

**Issue by ccsr** [apinf/platform#1048]
# User story

As an API consumer, I want to download code snippets of APIs in my programming language so that I can get a starting point for using the API in my application.

**Comment by bajiat** [comment]
Closing the issue, since Codegen is running on a server and code snippets can be downloaded in apinf.io.

Also, it is integrated to the APInf UI, since
* there is a setting for enabling Codegen in Settings in APInf UI for any deployment
* when Codegen is enabled, Documentation tab has Download SDK button for any API that as a Swagger file.
