### ISSUE TITLE
Combine analytics from multiple Umbrella instances to dashboard analytics

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1118]
_open issue: If we allow several Umbrella instancer (or other proxies) to one Apinf instance, do we need to be able to show analytics from multiple different proxies in one analytics page?_

**Comment by Nazarah** [comment]
Should we show the analytics in the same chart? or multiple one? I suggest a same chart with bigger view. Because there might be multiple proxies and adding up one chart for each proxy would take up a lot of space. Also for comparison, if we have good data representation technique, showing all the data in the same chart would be good.

**Comment by philippeluickx** [comment]
Should we remove the Dashboard 1.0 label so we can close the EPIC? This will have to be done with multiproxy...

**Comment by marla-singer** [comment]
@bajiat Have to be resolved in a new Dashboard
