### ISSUE TITLE
Create and publish rancher compose file for Apinf stack

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1125]
We would like to deploy Apinf on various servers using [Rancher](http://rancher.com/). In order to do this, a Docker/Rancher compose file would be useful. In addition to creating a [Rancher compose](http://docs.rancher.com/rancher/v1.0/zh/rancher-compose/) file, we should publish the file, so that it appears in the [Rancher catalog](http://docs.rancher.com/rancher/latest/en/catalog/).

**Comment by nnn** [comment]
@shaliko, what is the status of this task?

**Comment by shaliko** [comment]
@nnn Still in progress, have issue with first setup api-umbrella with api-umbrella.yml file. That file should be stored on persisted volume and mount to all api-umbrella containers for easy scale amount of containers.

Ideally we should release Apinf config in rancher catalog for easy setup it, but having api-umbrella.yml file instead of environment variables make configuration too complex, I trying find way for simplify it.

**Comment by shaliko** [comment]
related to https://github.com/NREL/api-umbrella/issues/286

**Comment by brylie** [comment]
Moving to icebox, since there has not been activity on this issue in 5 months.
