### ISSUE TITLE
ProjectLogo.files collection security

### ISSUE THREAD

**Issue by brylie** [apinf/platform#1426]
The ProjectLogo.files collection needs security rules, specifically for the following method:
- insert
- remove

Double check all collection security rules, to make sure only authorized users can perform database operations.

Remove this collection, if it is no longer useful.

**Comment by marla-singer** [comment]
@preriasusi Closed this issue because ProjectLogo collection has correct permissions
https://github.com/apinf/platform/blob/ce852bf7f099283c42999b437102625a947c11f3/apinf_packages/branding/logo/collection/server/permissions.js#L12-L25

CoverPhoto has correct permissions as well
https://github.com/apinf/platform/blob/ce852bf7f099283c42999b437102625a947c11f3/apinf_packages/branding/logo/collection/server/permissions.js#L12-L25
