### ISSUE TITLE
Unable to edit 'Username' in 'Profile' view

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#1507]
Resolution: Make the username field read-only.

Steps:  
1.Visit https://nightly2.apinf.io  
2.Create account by clicking on 'Sign up'  
3.Navigate to 'Profile'  view  
4.Edit username  
5.Click on 'Update' button   

Result: 
- Highlights 'Username' field with error message 'profile-usernameIsTaken'   
- Enter the previously given username and click on 'update' also shows the same error message.  
- Signout->Relogin->Go to profile view->shows the same error message.  

Browser:   
1. Mozilla Firefox 48.0  
(Mozilla Firefox for Ubuntu Canonical – 1.0 )    
2. Google Chrome 52.0.2743.116    

Operating System:  
Ubuntu 16.0 LTS    

Screenshot:  
![edit_username_error](https://cloud.githubusercontent.com/assets/13309358/18345101/9c1a2874-75c2-11e6-96a8-549a2b174adb.png)  

![selection_022](https://cloud.githubusercontent.com/assets/13309358/18345212/2f0abb3a-75c3-11e6-9ad8-95eedd23d8f3.png)

**Comment by Nazarah** [comment]
Ppossible suggestion: Make the username hardcoded, s.t. it appears in profile but it not-editable.

**Comment by bajiat** [comment]
@nnn Would you be interested in this task? Should be a small change to modify it as read-only.

**Comment by bajiat** [comment]
@nnn We had a discussion around this task and realized it needs to be possible to edit the username. We don't necessarily have a username (e.g. for users logged in with Github). Also, I came across a scenario where I would have wanted to change the username for a user created for a customer. So it would seem best to fix the original bug with user name editing after all. Can you investigate and give an estimate of how long it would take and would you be able to complete this task if we change the resolution to fixing the bug instead of making the field read-only?
