### ISSUE TITLE
UI for making API private for a user group

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1622]
In addition to being able to select between private and public, owner should be able to select that the API is public/visible to certain users: "private to a group".

# Definition of done
* [x] In the API profile, the owner can select that the API is private to a group.
* [ ] In the API Catalog, the owner can see an indication of 
  * [ ] completely private API
  * [ ] API being partially provate (visible to a selected group of users).

# Wireframes

1. API Visibility comes under Settings tab.
Has a separate Pane with radio buttons to select visibility option.
Default is public.
![closedapi](https://cloud.githubusercontent.com/assets/17976243/18913275/a907b77c-858f-11e6-8072-8cda502405cc.png)

2. To give access to specific people.
The section gets active when radio button is selected
Users can be added via email.
On adding a new user, they should appear as tags under the text field.
In API profile page , and API catalog, special icon should appear to indicate the API is visible for a specific group
(reference of BS tags: https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)
![closedapi2](https://cloud.githubusercontent.com/assets/17976243/18913739/240c6c22-8592-11e6-941e-23b26a0b9e13.png)

3. API is accessible only to owner
In API profile page , and API catalog, special icon should appear to indicate the API is visible only for owner
![closedapi3](https://cloud.githubusercontent.com/assets/17976243/18913742/2dfaea60-8592-11e6-8a14-de241edd3a47.png)

**Comment by bajiat** [comment]
@nnn Would you be interested in this task?

**Comment by Nazarah** [comment]
@nnn any design ideas about this issue?

**Comment by Nazarah** [comment]
@bajiat : currently we have a toggler in API profile to make an API public/private to the audience. Should this toggler still remain as we are changing the privacy option of an API?
Or it is going to be replaced by this issue?

**Comment by bajiat** [comment]
@Nazarah Toggler with three options? Can you sketch (even on paper) some options for the owner to select between the options?

**Comment by Nazarah** [comment]
@nnn based on a discussion with @bajiat and @jykae I prepared the given wireframes.
Please have a look and give your feedback

**Comment by nnn** [comment]
@Nazarah, really nice, love it!

**Comment by nnn** [comment]
One thing about the icons of indication. Let's use label instead of icons.
And only one label - **Private** if API is private to everybody and same label if available to some users. 
It will make UI look cleaner. Owners can always check who can see theirs API in the settings. There is no need to separately show these with different types of icons/labels.

**Comment by Nazarah** [comment]
@nnn agreed with the design suggestions.

**Comment by Nazarah** [comment]
@nnn I've got another suggestion, to change the API header, card and table row (in API catalog) color if an API is private. The label is good for profile header and table row, where more space is available. Am not just sure about the card view with little space.

**Comment by brylie** [comment]
...moving discussion here from #1623.

After our stand-up today, we reviewed the **API Visibility** feature/UI. @philippeluickx suggested, and we generally agreed, that the API Visibility selector should be a drop-down, rather than radio buttons. @Nazarah agreed to wireframe the select drop-down, as part of this task.

As an enhancement, we are discussing improving the drop-down by using an enhancement library, such as:

- [Bootstrap Select](https://silviomoreto.github.io/bootstrap-select/examples/)
- [Chosen](https://harvesthq.github.io/chosen/)
- [Select2](https://select2.github.io/)
- [Selectize](https://selectize.github.io/selectize.js/)

Using one of the above plugins would allow us to include the help text directly within the select menu, similar to how it is included among the radio select options:

![screenshot from 2016-10-04 13-46-14](https://cloud.githubusercontent.com/assets/17307/19071792/8aa14582-8a3a-11e6-8a79-68465098aa1b.png)
