### ISSUE TITLE
Set up product/ & project page

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1796]
Definition of done
- [ ] Set up a static site builder and template.
- [ ] Select theme that has the features we will need. 
  - [ ] Optionally, the theme could have a carousel
- [ ] Configure basic settings, like links to Github, social media, blog.
- [ ] Change background picture from generic picture e.g. to Mindtrek picture.
- [ ] Add one or two pages: basic information about the project and team.

![screenshot_20161020_154803](https://cloud.githubusercontent.com/assets/17307/19560400/0b133276-96dd-11e6-84ed-08ea1eb515b4.png)

**Comment by nnn** [comment]
@bajiat interested

**Comment by bajiat** [comment]
@nnn Can you add a link for Community? So that we can link e.g. to source code and Discourse

**Comment by Nazarah** [comment]
@nnn In your correct work of the website, there is a picture of APINF dashboard. Can you add a gif image there showing the charts interacting with each other?
It would give the visitors of a more practical and real-life example of how the dashboard functions.

**Comment by brylie** [comment]
Feedback and future enhancements:

- text/logo contrast is low on Hero page element
  - add shadow around text and logo (e.g. 2px/2px #333 or #ccc) for contrast
- Hero section may not need to be so large
  - consider how to shorten the 'hero' section, so that important information may be seen 'above the fold'
  - see, for example [IndieHosters](https://indiehosters.net/page/home)
- Feature headers 'API Owner' and 'Developer' are mixed up
  - match feature headers to their content
  - determine whether to show 'API Owners' or 'Developers' first
- Navigation menu `.active` color clashes with color palette
  - Change navigation menu `.active` color to match logo orange (#FF9D00)
- Light green color on open source section background clashes with other page colors
  - Create a consistent, complementary color palette for entire page
- Consider how to make features into clickable links
  - links should somehow show more detail about specific feature
- Documentation link is broken in open source section
- Consider adding a Testimonials section
- Consider adding a Sponsors section
  - add logos for companies who have sponsored our development process
- Add a contributors section
  - include names and possibly links to contributor profiles
- Remove Phone number from contact section
- Add link to Community.apinf.io to contact section
- Add link to Rocket.chat live chat in contact section
- Remove picture from 'About' section
- Add link to Sampo Software Oy in page footer
- Add 'Project' section
  - project timeline
  - developed by Sampo Software Oy

**Comment by bajiat** [comment]
To do list
- change logo to white?
- change the slogan to "Develop. We do the rest."
- add shadow around text and logo (e.g. 2px/2px #333 or #ccc) for contrast
- background picture/video: smaller so that it doesn't cover the entire screen
- Feature headers 'API Owner' and 'Developer' are mixed up
- background color for "We don't just talk about" from the same palette as other colors
- Keep only links Github and Community in the open source section
- Team: smaller pictures, name, title, apinf.io emails, Github, Medium or Twitter, if applicable
  AP Taija: provide a list of names and titles
- remove phone number from contact section
- Services section to be added (Taija and Chandra to help)
- Blog : change the link to https://medium.com/apinf
- Navigation menu `.active` color clashes with color palette
  - Change navigation menu `.active` color to match logo orange (#FF9D00)
