### ISSUE TITLE
HTTP Status Codes: Change the color of 2XX bar in the chart to green.

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#1811]
in General terms, green signals for everything OK.
Since 2XX response indicate success, so we should make it green than making it appearing grey.
# suggestions:
- 3XX: grey
- 4XX: yellow
- 5XX: red

**Comment by bajiat** [comment]
@Nazarah But isn't the 2XX bar green already? This is a screenshot I took from my browser:

<img width="444" alt="http codes screenshot" src="https://cloud.githubusercontent.com/assets/11626388/19682503/8817cee4-9ab6-11e6-87f6-e1b4fee57cc8.png">

**Comment by bajiat** [comment]
Actually, we have some kind of issue here. The color of the bar does not depend on the status code. It is somehow related to order of bars. If there is only one bar (4xx) in the chart, it gets green color regardless of the status is referring to.

<img width="437" alt="4xxgreen" src="https://cloud.githubusercontent.com/assets/11626388/19725894/e706d226-9b90-11e6-8de8-4454b3e782e3.png">

**Comment by marla-singer** [comment]
@bajiat @Nazarah Have to be removed in a new Dashboard
![joxi_screenshot_1504863620244](https://user-images.githubusercontent.com/20643403/30206004-67d221de-9493-11e7-90a5-9199cfbdef0a.png)

**Comment by marla-singer** [comment]
@preriasusi The issue is outdated and can be closed because there is the new Dashboard module
![joxi_screenshot_1512643539346.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff80161772227b52f77825d6ba7beb14394d4d1f0cf31b0d0c00eef39b2ea3b43f22df585fedd7395a76cf3812acb8d41eb857bd25995397f4edd4189fb5646fb2c99d452c1c051288fa5c37a69d48cd51f54be74d47e9.png)
