### ISSUE TITLE
Version number empty in About

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#1910]
The Apinf version number in About window is empty on staging (i.e. release 0.34), even though the about.html in master contains a version number (0.34). 

<img width="660" alt="about window release empty" src="https://cloud.githubusercontent.com/assets/11626388/20142345/fcb1d69a-a69c-11e6-855b-1ad57c58ebe7.png">

**Comment by brylie** [comment]
It turns out that the `package.json` file is replaced when we build the tool. Not only that, but when we deploy the platform, the working directory changes, so `proces.env.PWD` returns the wrong directory.

Changes needed may include:
- use `process.cwd()` to get current working directory
- determining how to retain pachage.json, or at least the project version number, when building for production

**Comment by brylie** [comment]
In the short term, we should probably revert this feature. That will mean updating the version number in two files, for each release:
- package.json
- .../about.html

**Comment by jykae** [comment]
Assigned by @bajiat
