### ISSUE TITLE
Rethink API dashboard

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2024]
As API owner I want overview. I'm interested about:

1. How do we perform? Give me indicators as numbers. Has the performance/usage changed past 7 days, 30 days? Amount of users? Has that changed past 7 days, 30 days? 
2. Then I want to see slow/failed calls and amount of them.
3. After that I want detailed views if even needed. Not always needed.   

## Additional item to discuss: API Manager view
I might have 20 APIs to manage. I don't have time to look at them separately. Perhaps we need API manager view in dashboard. In that view I get overview just for APIs I'm managing. 

Perhaps we can learn something from rather succesful product Plumbr. 
![kuvakaappaus 2017-02-04 09-54-15](https://cloud.githubusercontent.com/assets/1927158/22617900/3f3397d6-ead8-11e6-98b9-c44a85154365.png)

![kuvakaappaus 2017-02-04 09-55-15](https://cloud.githubusercontent.com/assets/1927158/22617901/451d7f86-ead8-11e6-8c91-bbccd8f5304f.png)

![kuvakaappaus 2017-02-04 10-01-05](https://cloud.githubusercontent.com/assets/1927158/22617903/4cba8130-ead8-11e6-8dc4-a4ba0973d9e8.png)

**Comment by Nazarah** [comment]
@kyyberi : thanks for suggesting Plumbr.
Tried to go through your screenshots.
I liked the idea about how they have used different colors and simple graphs to relay information.
I however, would not agree to put so much information in the 1st view loaded to an user.
Too many information, their visualization would be a cause for distraction so API manager would not be able to concentrate just on one thing.

"I might have 20 APIs to manage. I don't have time to look at them separately. Perhaps we need API manager view in dashboard. In that view I get overview just for APIs I'm managing."
Referring to this requirement, it is not possible for humans to go through and recall more than 5 things at a time (from some cognitive UX studies from my degree). Even if we agree to show API specific information, we need to which information is more important to API manager (e.g. no. of requests, response rate, average response time, etc.) and then display them with the order of importance.
We can always give API manager a choice fol selecting a max of 5 APIs to appear by default and s/he can always customize it. But then again we need to have a way to see information about other APIs.

For selection of time period, I think API manager might be more interested to get information about last 24 hours/last week/last month rather than last 4 hours or any other numeric values like this. Always it is good to have a date range picker so that manager can get his/her own preference timeline.

I'd be providing some low fidelity designs with the ideas that I have on my mind. :)

**Comment by kyyberi** [comment]
As a API manager I wish to see overview of my APIs. If all seems "green" I can focus on other stuff. If some of them show "yellow" I know that something requires my focus and then I dig deeper to that specific API. If there's "red", I know that I need to put my whole focus on that API. Perhaps organisation view could function as starting page for API manager? In there I could see status of API behaviour as "colors". From there I could select what ever API to see more details. On organisation level I could have overview / statistics view from all our APIs as numbers? Lets discuss this a little more :) Anyway, my point is priorities. API manager does not drill down to details unless it's necessary.

**Comment by philippeluickx** [comment]
I think there are some good points here. I would love to go over the whole service from a "service design" perspective. What are the jobs each role needs to do and how can we design for those.
Maybe we should also update our personas?

**Comment by Nazarah** [comment]
It would be good to have the research and work based on service designing. Often it helps to focus down on to the most important and minimalistic features. And there is possibilities to add/modify personas accordingly.
I recommend to use this free template from http://thisisservicedesignthinking.com
We used this one in our school works, but is good enough to be used for APInf as well

**Comment by bajiat** [comment]
@philippeluickx I think it would be a good idea to update our personas. We worked with the personas at the very start of the project and - hopefully - have learnt a lot since. They were a starting point, but don't suffice any more.

**Comment by bajiat** [comment]
If I would be an API owner or an organization manager, what are the questions I would like to get answers for?

Some suggestions:
Is there a problem I need to address immediately? (E.g. high amount of failed or slow calls)

**Comment by bajiat** [comment]
Comments from dashboard meeting (@Nazarah, @55, @bajiat)

### If I would be an API owner or an organization manager, what are the questions I would like to get answers for?
 * Is there a problem I need to address immediately or soon? (E.g. high amount of failed or slow calls) Where is the problem (which API, endpoint)?
* How popular are my APIs? Nr of calls, nr of users or applications
* Which APIs or which endpoints are popular (in comparison to others)?

### What are the habits of API owners?
* How often do you go to check the dashboard? Once a day? Several time a day? When? (Does that depend on whether we have notifications for problems?)
* What should be the default time for instance for total number of calls? 
* Should the dashboard be the default view for owner and organization manager?

### Interaction options with charts
- direct interaction with the charts
- menu to select from (menu appears only if you decide to open it), this would also allow some premium features in dashboard, which are inactive if you are not a premium user. Menu does not mean only possibily to select one API, but rather it means more filtering criteria and combining the criteria. 
- ready-made queries: e.g. most popular API for a week (+ some other search criteria)

**Comment by Nazarah** [comment]
@ashakunt as an API owner of a number of APIs, what things you prefer to know determine which APIs might need your attention and the necessary actions to take?

**Comment by ashakunt** [comment]
@Nazarah : I will check this thoroughly during monday, tuesday and provide feedback.
