### ISSUE TITLE
Admin Dashboard:'Select API' list not segregated

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2042]
_From @saralavanip on December 15, 2016 11:23_

# Steps  
1. Visit https://staging.apinf.io  
2. Login as admin  
3. Navigate to'Dashboard ' 
4. Click on 'Select API' drop down menu   

# Expected Result  
Show the segregated list of APIs: 'Admin APIs','My APIs' and 'Other'   

# Actual Result  
API list not segregated. It shows all APIs as 'My APIs'   

# Screenshot 
![dashboard_only_myapis_list](https://cloud.githubusercontent.com/assets/13309358/21222245/a49ccd68-c2c9-11e6-9924-45090a885a93.PNG)

_Copied from original issue: Digipalvelutehdas/APIKA#150_

**Comment by marla-singer** [comment]
@bajiat THese part is gone in a new Dashboard

**Comment by marla-singer** [comment]
@preriasusi The issue is outdated. The new Dashboard module has the groups for Admin users
![joxi_screenshot_1512640551197 (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46e29b822abd90aa9decba4db755ff80161772227b52f77b25d0b279e6153b495e465cb053181d1ba6acda6fb4bc2e758f5e08bf84690b74c06914aeb1871cbf01ec218c1982b3ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4aca5ef24ae64d53a7153471ab.png)
