### ISSUE TITLE
UI changes based on normalization task

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2185]
Related to #2184

# Goal
API metadata contains information about organization and organization contact person, if API is connected to an organization
Migration is handled, if needed

# Definition of done (TBD by assignee)
- [x] Display all available information about connected Organization in API Metadata tab: Name, description, url
- [x] Organization name should be as a link to organization profile (optional)
- [x] When a user connects API to an organization, API Metadata contains information about these organization
- [x] When a user disconnects API from an organization, API Metadata doesn't contain information about these organization

**Comment by bajiat** [comment]
@marla-singer This is related to #2184, so could you take this one as well?

**Comment by marla-singer** [comment]
@bajiat Done

**Comment by marla-singer** [comment]
@bajiat I suggest using all profit from linking ApiMetadata and Organization collections. For example, add URL and Logotip in ApiMetadata section which will be able from organization document.

**Comment by bajiat** [comment]
@marla-singer We are experimenting with a process that each assignee creates the definition of done based on the goal of the task after the task has been assigned. Please create a definition of done and include also your ideas from the comment above. We can review and comment.

**Comment by marla-singer** [comment]
@bajiat If API metadata doesn't exist and API is already connected to an organization. What to do? Create the API Metadata document by hand in code?

**Comment by bajiat** [comment]
@marla-singer Definition of done seems ok.

> If API metadata doesn't exist and API is already connected to an organization. What to do?

In which situation this would occur?

**Comment by marla-singer** [comment]
@bajiat 
-  For example, you have an API without API Metadata. 
![joxi_screenshot_1489390203919](https://cloud.githubusercontent.com/assets/20643403/23845245/0b283f74-07d8-11e7-9147-9434782ed0df.png)

- You decide to connected your API to an organization. Navigate to `Settings` tab, select the organization, the message about success operation is displayed.
- You navigate to `Metadata` tab. What are expected to see?

1. Empty page because Metadata document was empty before
![joxi_screenshot_1489390203919](https://cloud.githubusercontent.com/assets/20643403/23845266/21bc1490-07d8-11e7-9fce-2a916462f3f5.png)

2. Created page with organization data. In this case, the document will be created by the programmer behind the scene.
![joxi_screenshot_1489390301812](https://cloud.githubusercontent.com/assets/20643403/23845290/46a245a4-07d8-11e7-90dc-5d332ae1f539.png)

**Comment by marla-singer** [comment]
@bajiat Can you please describe the steps of **"How to demo"**? I'd like to see what do you expect from this feature and how will it work?

**Comment by bajiat** [comment]
Option 2. 
If the organization already had other information besides the name, then that too.
