### ISSUE TITLE
'Apinf community' link not responding

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2215]
# Steps  
1.Visit https://nightly.apinf.io  v 0.41.0  
2.Go to 'Find Us'  
3.Click on  'Apinf Community'  

# Result  
'Apinf Community link not responding    

# Screenshot  
![apinf_community_error](https://cloud.githubusercontent.com/assets/13309358/23499178/c3b9a4cc-ff33-11e6-85fd-38b254958d29.PNG)

**Comment by saralavanip** [comment]
Verified this issue on staging v 0.41.0 and it is reproducible.

**Comment by saralavanip** [comment]
@bajiat , re-checked with Github link:  
- login as admin->Branding->Social Media->Select Github and Add URL -> Result: Github link working  as expected

**Comment by taija** [comment]
@saralavanip - I think you tagged the wrong person earlier; not involved with this project 😃

**Comment by saralavanip** [comment]
@taija, sorry , please ignore and thanks for letting me know :)

**Comment by manzapanza** [comment]
@saralavanip The community link doesn't works because the ssl certificate, configured on the server that hosts the website, is not valid.

For example Firefox shows this error:

![selection_128](https://cloud.githubusercontent.com/assets/1139716/24797423/99f86560-1b67-11e7-8670-1aa577c5479e.png)

So, this bug is not related to the apinf platform.
