### ISSUE TITLE
User accessibility: user can add API when settings don't allow that

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2220]
In the process of working on #2056 issue, there were found the bug with user accessibility.
- if **`Only platform administrators are allowed to add new APIs`** option is checked nevertheless a user can add API via URL `https://nightly.apinf.io/apis/new`.
- Case: the user doesn't have any API and  **`Only platform administrators are allowed to add new APIs`** option is checked. The User has access to Dashboard page via URL and can click on `Add API` button.

### Part 1
1. Sign in as administrator
2. Go to Settings page
3. Set enabled for "Only platform administrators are allowed to add new APIs" in Adding APIs block
![joxi_screenshot_1489157813522](https://cloud.githubusercontent.com/assets/20643403/23799825/fdd66d2e-05ba-11e7-894d-5bf07ae9e327.png)
4. Save settings

### Part 2 
1. Sign in as ordinary user without administrator role
2. Make sure you don't have button "Add API" in navbar (it's expected)
![joxi_screenshot_1489158028926](https://cloud.githubusercontent.com/assets/20643403/23799948/7a28fe14-05bb-11e7-9b64-d781cb4f0ddd.png)
3. Navigate to `http://localhost:3000/apis/new` (or insert your localhost domain)

### Found
- A user can see form for filling data and can add new API

### Expected
- Show to users message with 403 message as we have for private api when user try to navigate to Private API via directly URL
![joxi_screenshot_1489158328865](https://cloud.githubusercontent.com/assets/20643403/23800130/2bf4f580-05bc-11e7-84cd-16edda6b1854.png)

**Comment by bajiat** [comment]
@marla-singer Could you please add steps to reproduce? I'd like to assign the issue to @snittoor

**Comment by marla-singer** [comment]
@bajiat Done
@snittoor If you have the questions about step, you can write me

**Comment by bajiat** [comment]
@marla-singer Thanks!

**Comment by bajiat** [comment]
Copying comments from #2361.

Comment from @snittoor
Issue:
  The code in the function userAddApi () in apis/client/lib/router.js , the Settings.find() is returning undefined. Can someone help why is it happenning?

Test Case failing:

1) If user is NonAdmin and  singleSetting.access.onlyAdminsCanAddApis = true .. then not authorised. This is failling because settings.findOne is returning undefined.

Comment from @brylie:

I am fairly confident that [we can use Meteor methods inside of FlowRouter actions](https://github.com/apinf/platform/blob/develop/apis/client/lib/router.js#L38), meaning we can delay the rendering of the template while we check whether the user is an Admin.

**Comment by bajiat** [comment]
The branch used to solve the problem earlier (related to PR #2361) has not been deleted.
