### ISSUE TITLE
Consolidate organization settings into one place

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2317]
# Goal

* All organization settings can be found from one place: the settings tab. This includes the settings in the header area
* Thee settings are organized in a meaningful way.
* There is a panel / group for (organization page) branding configuration panel in the organization settings.

# Definition of done
* [ ] All organization settings can be managed via Organization Settings tab 
* [ ] Organization Settings tab is laid out new way according the wireframe
* [ ] Organization settings are stored into database
* [ ] No Organization Edit button exists any more
* [ ] No possibility to modify Organization settings via modal any more
 

# Wireframe
![organizationsettings4all](https://cloud.githubusercontent.com/assets/17976243/24240732/51d8f734-0fbb-11e7-9ef5-24425145b5cd.png)

Items in the Setting tabs are organized as the following sections:
* **General**
- Organization Name
- Organization URL
- Description
- Logo Uploader
- Cover photo Uploader
* **Social Media Platform**
- Facebook
- Twitter
- Instagram
- LinkedIn
* **Contact Information**
- Contact Person's Name
- Phone
- Email
* **Content Management**
- No. of APIs to appear in default view
- No. of media Content to appear in default view
* **Adding Organization Managers**
* **Deleting Organization**

The bootstrap panels are removed from the design the keep a simple and clean view.
Instead, Header texts (h3) can be used to distinguish between sections with whitespace separating one section from another.
Separate sections are a preferable choice if in future new items needs to be added in settings tab.
Except for Organization Managers and Delete Organization sections, Save and Cancel buttons appears at each section.
[**Open Question:** Would it be possible to add  Global Save and Cancel buttons for General, Media, Content Management and Contact Information sections?]

**Comment by nnn** [comment]
Interested.

**Comment by Nazarah** [comment]
@bajiat : Settings for a specific organization will also prevail in respective organization profile page under Settings tab right? So that organization manager can configure this from the profile page. If I am not wrong, then the Branding menu under user profile is accessible only to APinf admin. Please correct me if wrong.

**Comment by bajiat** [comment]
@Nazarah: Branding here refers only to organization page branding: cover photo, logo, nr of items etc.

**Comment by Nazarah** [comment]
@matleppa @bajiat 
The wireframe is attached in the issue.
Please have a look and give me your feedback

**Comment by Nazarah** [comment]
@matleppa please consider adding more white space than what is shown in the wireframe, so that the sections are easily distinguishable from each other.

**Comment by matleppa** [comment]
After discussion @Nazarah @matleppa a decision was made concerning save and cancel buttons in wireframe. 

Save button: 
Only one save button, which is common for sections General, Social Media Platforms, Contact Information and Contact Management.
 
Cancel button:
No Cancel button because there is no history for field values, thus previous values can not be restored.

**Comment by brylie** [comment]
@bajiat after a discussion with  @matleppa and @nnn, we realize that it might be necessary to exclude the **Content Management** section from this task.

![screenshot_20170331_151618](https://cloud.githubusercontent.com/assets/17307/24550056/00b81f0e-1625-11e7-9e33-63c1d4cdc2f5.png)

The reason is that the **Content Management** functionality is not fully 'baked'. Moving the content management section to a follow-up task might allow @matleppa to complete this task sooner.
