### ISSUE TITLE
Title bar and navbar

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2371]
# User story

# Goal
* Both title bar and navbar should be sticky
* Keep in mind mobile-first approach
* Title bar should contain the logo and the Sign in link. Remove language selection. (Language selection to be moved to footer in separate issue.)
Navbar
  * Anonymous user should be able to go to Catalog or Manage APIs from navbar
    * Open issue: Where shoud Manage APIs lead to: additional information for manager + sign in or sign in and Add API
  * About should be removed from the navbar for both anonymous and signed-in user (Separate issue to add About to footer)

# Wireframe
laptop view
![frontpage1-3](https://cloud.githubusercontent.com/assets/17976243/24896023/c194e9a4-1e9b-11e7-8ba1-ced0ec6a7de5.png)
<br></br>
<br></br>
mobile view
![mobile1](https://cloud.githubusercontent.com/assets/17976243/24896049/de189b16-1e9b-11e7-8ae9-5c3cb9f3a538.png)

**Comment by nnn** [comment]
Interested.

**Comment by Nazarah** [comment]
@nnn can we try out with something like this?
![navbar](https://cloud.githubusercontent.com/assets/17976243/24741053/eacf8ce0-1aac-11e7-9c93-8d7a0e97556e.gif)
This is convenient if a nav bar has more menus to display (either on the front page or signed in session).
We even won't need to use a hamburger menu to display all the option.

Another thing is to incorporate a small search option on the top menu (placeholder for APInf logo and sign in option).
Since we are more focusing on API consumers who would like to look for documentation, this would be convenient for them to access the search option anytime they want.
