### ISSUE TITLE
Dashboard stops working properly after 50 000 hits

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2456]
## Description

I generated traffic to avoindata.net API with some scripts (10 pcs running in parallel generating >some thousand hits per hour).  In the morning I noticed that charts are not shown, I have no idea of the real call amount (since all I see is 50 000 hits, which is not true). 
![50000](https://cloud.githubusercontent.com/assets/1927158/25033438/39ceb5d4-20e6-11e7-9c96-ece92578f162.png)

**Comment by kyyberi** [comment]
In addition in the charts I only see Fri 14 even though I demanded to see 11.4.2017-14.4.2017. Expected: show the requested timeframe in the chart.

**Comment by kyyberi** [comment]
I took offline a few scripts and thus dropped the traffic amount. After that I was able to see chart with hour granularity. 
![kuvakaappaus 2017-04-14 08-26-18](https://cloud.githubusercontent.com/assets/1927158/25034033/2d552058-20ec-11e7-98b0-a52be9a89295.png)

This 50k limit seems a bit ridiculous. For example one of our prospect customers has 14 000 000 / month. We must be able to show charts for high traffic APIs. Find a way.

**Comment by brylie** [comment]
> We must be able to show charts for high traffic APIs. Find a way.

After researching and discussing this issue in issue #1340, we agreed to use Elasticsearch directly for dashboard data aggregation. The resulting work means re-writing our dashboard code, including each chart and related data aggregation. We will continue the work, but have to see where it fits in the project roadmap/priorities (@bajiat, @ccsr).

@frenchbread in what task/discussion did you show us the Elasticsearch aggregation performance benchmarks?

**Comment by frenchbread** [comment]
This one: https://github.com/apinf/emq-analytics-dashboard/pull/7

It's for EMQ dashboard though, but we can use it as a reference. Moving towards using ES aggregated data on APInf dashboard means getting rid of data-table at some point.

**Comment by philippeluickx** [comment]
So basically we need to have a prioritization discussion. This has been on the table for way to long.
I'd rather have no analytics than the current implementation. I consider this feature broken.

@bajiat @kyyberi would this get top priority over the other tasks? I've been +1 on this for almost a year now.

**Comment by brylie** [comment]
> I'd rather have no analytics than the current implementation. I consider this feature broken.

Lets keep the conversation and feedback **constructive**. That is a really strong statement with very little foundation. It doesn't really suggest any helpful way forward.

**Comment by philippeluickx** [comment]
I am being constructive here and clearly own my statement. For me this feature is not done. It allows me to more easily prioritize it when looking at it this way.

As to the investigations done so far, I am very happy to see we are making progress to a workable solution. I would like to understand how come we did not push to the end and managed to close this issue? It's been on the radar for months.

**Comment by brylie** [comment]
> I am being constructive here
By **constructive**, I mean 'suggest a way forward' rather than simplay stating the current solution is inadequate and might be better to throw away.

Some ways to give constructive feedback:
> - Be focused. No hinting. No generalizations. Be specific. Use concrete examples
> - Don't ask too much. Set realistic goals.
> - Be a guide. Supply feedback and suggest a course of action
>
> Inc. Magazine [How to Give Constructive Feedback](https://www.inc.com/yael-bacharach/how-to-give-feedback-developmental-conversations.html)

>  I would like to understand how come we did not push to the end and managed to close this issue?

We have some process and prioritization challenges to overcome. For the past year we have been scrambling to keep up with incoming, Epic level, requirements from several sources. This is still ongoing, and perhaps growing stronger, as can be evidenced from our Roadmap above.

**Comment by marla-singer** [comment]
@bajiat This bug is resolved in a new Dashboard and can be closed
![31215001-8e272e00-a9b6-11e7-8bf0-885d00aba7ba.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46bbc5c872d7d3f9dea4e746f60aa29179166a727006f56621d4e67ff21a79075f4246a4440c5f44adabd82cf4e72e6c981c49b28b380c30d43703a9bd801ced54be748b49d1b3be8349c3e83d73e68cd9483b0c190acbae0361ffc412820db459eb5f54a3193766e67137754f911a7225696434e6.png)

**Comment by marla-singer** [comment]
@preriasusi  This bug is resolved in a new Dashboard and can be closed
![31215001-8e272e00-a9b6-11e7-8bf0-885d00aba7ba.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57e2814d778e3d0f005c2de7/125516c66e82c728ace21e0d46bbc5c872d7d3f9dea4e746f60aa29179166a727006f56621d4e67ff21a79075f4246a4440c5f44adabd82cf4e72e6c981c49b28b380c30d43703a9bd801ced54be748b49d1b3be8349c3e83d73e68cd9483b0c190acbae0361ffc412820db459eb5f54a3193766e67137754f911a7225696434e6.png)
