### ISSUE TITLE
Move frontpage numbers/statistics after search section. 

### ISSUE THREAD

**Issue by kyyberi** [apinf/platform#2499]
From sales point of view putting the numbers bar after the search box in frontpage makes more sense than hiding the key numbers somewhere at the bottom (nobody sees them). 

Having the numbers at top gives the newcomer reason to go forward (as soon as the numbers have grown). Numbers convince and give credibility.

**Comment by kyyberi** [comment]
Ping @Nazarah @bajiat

**Comment by Nazarah** [comment]
I actually have a bit different POV on this.
To me, placing this statistics in the beginning of page would suit better in our organization page.
The reason is that people might 1st visit the company page to know about the product, what it does. In that context, giving overview information at the beginning helps in getting people's trust.
When their curiosity builds,   they would go to the platform front page.
And our current aim with the platform front page is to help people discover APIs and learn about API management. 
So, we have placed recently added APIs after search functionality.
Users can scroll down and find the same statistics in the next section.
So I propose to have this issue for APInf company web page.

**Comment by kyyberi** [comment]
Well. I gave my point of view :) I understand that there are different opinions and viewpoints. However, when a person is "selling" our product, they dont show company website, but the product. Show me the product is the first question. Logged in user UX might differ from others regarding frontpage.
