### ISSUE TITLE
Develop Users API

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2501]
We need API endpoints to access and manage APInf users.

# Goal
- Review the APInf data model for alignment.
- Define endpoints and methods.

# Related resources
We have produced a Swagger file with Users API endpoints, which can be accessed on our [APInf deployment](https://apinf.io/apis/apinf-catalog-rest-api).

This is also related to issue #2440

# Definition of Done
- [x] API can return all users (default limit is 100, default sort option is ascending by username).
- [x] API can return users sorted by  username / creation time / update time
- [x] API can return given number of users per response
- [x] API can return users beginning from given position
- [ ] Create Swagger  Documentation

**Comment by Nazarah** [comment]
added draft swagger file: https://github.com/apinf/docs/blob/master/docs/develop/REST-API/APInf-User-API-MVP-swagger.yaml

@matleppa @jawidahmadi the file needs revision

**Comment by brylie** [comment]
It is worth noting that the Users API may already exist. By default, [Restivus creates a basic Users API](https://github.com/kahmali/meteor-restivus#users-collection-endpoints).

It is also worth understanding the difference between `api.addCollection` and `api.addRoute`:

- [Defining collection routes](https://github.com/kahmali/meteor-restivus#defining-collection-routes)
- [Defining custom routes](https://github.com/kahmali/meteor-restivus#defining-custom-routes)

**Comment by matleppa** [comment]
While wondering why Users routes are not included in generated swagger document I looked at code of restivus-swagger (restivus-swagger/server/restivus-swagger.js), where I found this:

          // Exclude swagger, login, logout, users paths, and routes with option hidden set to any truthy value
          if (route.path !== swaggerPath &&
            route.path !== 'login' &&
            route.path !== 'logout' &&
            !route.options.hidden &&
            !route.path.includes('users') )
          {

 So it seems that because user path documentation is intentionally excluded, in this issue the DoD point create swagger documentation can not be fulfilled.

**Comment by matleppa** [comment]
All requirements described in the Swagger file with Users API endpoints can not be met, at least not at this time.
- sorting by updated_at parameter has no effect because there is not respective field in Users collection 
- route users/updates is returned based on field createdAt, because of lack of updatedAt field in Users collection
- order of sort parameters does not affect the multilevel sort
- organization name given as sort parameter has no effect in sort
- because user can belong to several organizations, the functionality of organization name as a sort parameter needs to be replanned
