### ISSUE TITLE
Document steps about git rebase do contributor guidelines

### ISSUE THREAD

**Issue by brylie** [apinf/platform#2524]
DevOps team has explained the importance of our Git history. As a simple practice, our developers need to start using rebase. Add instructions to our [contributing guidelines](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md) regarding rebase, with simple example(s).

**Comment by ashakunt** [comment]
The idea behind the importance of Git history (to name a few) is that:

1. A clean log allows easy tracking of project over time
1. Allows using tools like `git bisect` without any hassle
1. Reduces conflicts during merging the `feature` or `hotfix` branches to `develop` branch

Further, since we would be getting closer to supporting multiple releases and for different customers, it makes a lot of sense to have a code where backporting of minor security fixes is possible. I hope that all of us here appreciate the fact that when merging a PR or even cherry picking a security fix, the whole process should not take more than hitting enter on the relevant command. A relatively linear history allows this to happen with minimum or less hassles.

**Comment by mauriciovieira** [comment]
> As a simple practice, our developers need to start using rebase.

I would say some people have been using rebase in the team, but it's not a common practice.

One other point is the quality of git messages. As I said on our chat in March,

> Also, I would like to suggest the reading (and adoption) of https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

I totally agree with @ashakunt on his last comment. Thanks for bringing this up, and sorry for coming late for the discussion.

**Comment by ashakunt** [comment]
This comment focuses on `git rebase`:

One of the most powerful features of git is the ability to commit often, fix history if needed and push once done. In all the **personal feature branches** we should use this strategy. So, when a feature has to be developed this is what we should follow (some of if we do already): 

* [x] Create a feature branch for all the development
* [x] Do all the development in the feature branch 
* [x] Merge to `develop` once the feature has been **DONE**

In a continuous development environment, there are chances that the `develop` will be updated before a developer finishes his/her feature. So, the following thumb rules should be applied: 

1. **A rebase a day keeps conflicts away**: I would recommend to a developer that they should rebase their branch _(= update your branch w.r.t. latest develop)_ once every morning before they start their regular work. 
1. **A rebase must be performed before creating a PR**: Trust me, you will thank me for this. Always.

An example for rebase is given below (with a new repository and using master instead of develop, apologies ;-) ).

![image](https://cloud.githubusercontent.com/assets/5460151/25945611/397f3bba-3650-11e7-9fd0-f5e6b73e2a08.png)
^^ above:
* New repo was initiated
* Initial commit was added to master
* Feature branch `feature-01` was created and completed
* Assumption is that there might be new commits in `master` by the time `feature-01` is finished.

![image](https://cloud.githubusercontent.com/assets/5460151/25945732/b2c2250a-3650-11e7-94c0-7d9713047bf3.png)

^^ and there are new commits in master. We should update our `feature-01` branch w.r.t. latest in `master`

![image](https://cloud.githubusercontent.com/assets/5460151/25945923/8080305e-3651-11e7-82ce-f7c92ac7b272.png)

^^ `feature-01` before `git rebase master`

![image](https://cloud.githubusercontent.com/assets/5460151/25945947/9160cb22-3651-11e7-9431-ee8d1d84599d.png)

^^ Initiated `git rebase master` and state of the feature branch after the rebase. As you can see that the `commit c59309b` has been applied to `feature-01` and then, the implementation of `feature-01` is applied to the tree.. **This is how we should follow**. 

Remember that at this stage, you might also get conflicts and you should **resolve the conflicts here**. Once the `feature-01` has been updated w.r.t. `master` (and in our case, w.r.t. `develop`), then a PR must be made from `feature-01` -> `develop`. 

![image](https://cloud.githubusercontent.com/assets/5460151/25946082/38cddb2a-3652-11e7-9b4b-696703e7c6ab.png)

I think Github already uses a --no-ff merge strategy so, we need not worry about that.

**Comment by ashakunt** [comment]
Some situations to handle: **when one developer is working alone on a branch**

1. You committed some stuff last evening
1. This morning when you rebase your branch w.r.t. `develop`, you find new changes 
1. Your feature will not be finished today; so you need to push all the changes at the end of the day and come back later

At this point, in the evening, when you do a `git push`, server rejects your changes because the history has changed (because of the rebase and updates in `develop`). 

**IMHO, its ok at this point; if you are the only developer working on this feature branch, to do a `force-push`**

**Comment by ashakunt** [comment]
>  Since people would be working on the feature branches, its my personal opinion that its ok to do a force push only in the feature branch.

^ I am however open to any better recommendations. @mauriciovieira @phanimahesh @philippeluickx @brylie.

**Comment by ashakunt** [comment]
Some handy `git shortcuts` you might want to use: 

**`git lol`**
`lol = log --graph --decorate --pretty=oneline --abbrev-commit` <- shows a command like graph pretty similar to gitk. 
**`git in`**
`!git fetch && git log --pretty=format:'%C(yellow)%h%Creset: %Cblue%an%Creset %s' --abbrev-commit --graph ..@{u}` <- checks if there are any incoming commits in the remote tracking branch
**`git out`**
`log --pretty=format:'%C(yellow)%h%Creset: %Cblue%an%Creset %s' --abbrev-commit --graph @{u}..` <-- checks if you have something you should push to the tracking remote

An important thing to remember is that when in the morning the developer does a `git rebase` he should run the `git pull` first. As a thumb rule, they should always run the `git pull` after checking out to the `develop` branch. If you want to save your work (and do not commit), use `git stash` or create a temporary commit and come and talk to me if you want to `edit your git history` (`git rebase -i`).

**Comment by ashakunt** [comment]
Please review and if you think its ok, we can close this issue.

**Comment by mauriciovieira** [comment]
@ashakunt Firstly, thank you for documenting this way. I think it's a good idea to have these guidelines on our CONTRIBUTING.md or on some separated documentation just for it.

I've been rebasing and force-pushing on my branches since the first commit I've done to this repository, in 2015. I experienced no big problems on doing it. In practice, all feature branches are treated as personal branches and whenever a person want's to contribute to another, they've been opening a new pull request *from* a branch derived from a feature branch *to* the former (and not develop).

> Remember, **NO FORCE PUSH IN `develop` or `release` or `master`**

The easiest way to make sure is to protect these branches on github.
