### ISSUE TITLE
Branching strategy

### ISSUE THREAD

**Issue by philippeluickx** [apinf/platform#2537]
After discussion with @phanimahesh concerning our CI flows, we might want to rethink our branching strategy to align both development and CI.
@phanimahesh suggested workflow:
http://nvie.com/posts/a-successful-git-branching-model/
https://github.com/nvie/gitflow

It's a strategy I've seen working in bigger companies.

**Comment by brylie** [comment]
We are already following GitFlow. We just mainly work with feature [branches](https://github.com/apinf/platform/branches). See our [Contributor guide](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md#contributing-code) for details.

**Comment by brylie** [comment]
That said, there are always possible improvements to the process. One improvement would be that we release more patch level fixes (i.e. hotfixes in Gitflow parlance). That would allow us to get bug fixes to production faster, so we can get code to clients/stakeholders as fast as possible.

**Comment by brylie** [comment]
On a more general level, this issue is an example of assuming things should be different without checking how they actually are. We can certainly improve, but need to understand how things currently work before suggesting changes. This is a common pattern for people first joining a team/organization/process, where they suggest the organization should adapt to their previous experience before learning how the process is already working.

**Comment by philippeluickx** [comment]
@phanimahesh Could you please join in?
@brylie The discussion got started in the context of CI and it seemed there are no release branches. I haven't seen a lot of hotfix branches either. It seems to me we are using a subset of Gitflow.
Like you said, are there any improvements we can adopt? As I understand it, e.g. release branches will make the CI easier.

**Comment by brylie** [comment]
> there are no release branches.

Github uses tags for releases:

> Versions are based on Git tags.
> 
> Github Help: [Creating releases](https://help.github.com/articles/creating-releases/)

**Comment by brylie** [comment]
Basically, we all agree to make hotfixes more often. Lets start with that.

**Comment by bajiat** [comment]
@ashakunt This is something you probably want to comment as well.

**Comment by brylie** [comment]
@apinf/architects, @apinf/core, @apinf/developers : today in stand-up we agreed to make any small bug fixes, going forward, against the `master` branch (as hotfixes). This will align our process more deeply with Gitflow, and allow us to quickly deliver bug fixes to clients.

**Comment by brylie** [comment]
@bajiat, @phanimahesh, @philippeluickx, @ashakunt lets discuss starting next sprint with a release branch.

**Comment by phanimahesh** [comment]
Feature branches are a natural consequence of having multiple developers.
They isolate feature changes so that each one is unaffected by others. We
can not claim to be following git flow pointing at just feature branches.
It is just basic version control hygeine.

Releases must be tagged. Github got it right. No arguments there either.
Release branches do not replace tags.  They complement each other.

Let's say we make a release, and sometime down the line we need to patch it
for a customer who can not upgrade. Or we need to backport a fix to older
releases. There is only one way to handle this sanely when it becomes
anything more than a one off thing. Release and hotfix branches.

There are two components to git flow. The branching model (structuring the
commit graph) and the branch naming conventions. The only recommendation of
git flow we follow is feature branch naming convention.

It is good that we do feature branches, follow common naming pattern for
feature branches, and have work in progress pull requests, but from a
release management and CI perspective these are not sufficient.

I believe it would be good for everyone to spend time reading about or
revisiting git flow, and understanding why it recommends the things it
recommends, before continuing this discussion.

P.S: I'm travelling back to India so may not be able to respond until
tomorrow.

**Comment by brylie** [comment]
> The key moment to branch off a new release branch from develop is when develop (almost) reflects the desired state of the new release.
> when a release branch currently exists, the hotfix changes need to be merged into that release branch, instead of develop
>
> [A successful Git branching model](http://nvie.com/posts/a-successful-git-branching-model/)

After more closely reading that article, I am still confident we can start making hotfixes this sprint. We will just need to decide whether to sync the changes with `develop` based on the existence of a possible release branch.

**Comment by philippeluickx** [comment]
Starting with hotfixes definitely gets a +1 from me and seems like a non-disruptive change to our processes.
Release branches is a different story. I wanted to start the discussion after talking with @phanimahesh, which is happening here and that's great. Kudos to @phanimahesh in clarifying, appreciated.

**Comment by brylie** [comment]
Cool beans. I just opened a [hotfix pull request](https://github.com/apinf/platform/pull/2540) for our blank-dashboard issue.

**Comment by ashakunt** [comment]
Hello, I am joining this discussion a bit late, but better late than never. My comments below with some references from https://datasift.github.io/gitflow/IntroducingGitFlow.html and a tiny bit of my experience in dealing with some projects which are bit bigger than `apinf/platform`: 

With a distributed team like ours, parallel development (which is an excellent practice) is unavoidable. The team is already following the practice of working in `develop` as our `staging` area and subsequently, developing all the features in `feature branches`. **Kudos to the team**. 

Having said that, I agree with @philippeluickx that we are using a subset of GitFlow; and with @brylie that it is possible to improve the process. 

Scope of improvement here is to (keeping in mind release management, CI): 

1. [ ]  start using `release` branches along with `release` tags
1. [x] emphasize working in `feature` branches as the thumb rule (and we already do that)
1. [ ] use standard `git` practices, that will be documented in https://github.com/apinf/platform/issues/2524 and subsequently added to [contributing guidelines ](https://github.com/apinf/platform/blob/develop/CONTRIBUTING.md)

Referring to the "**hotfix**" discussion: I strictly disagree with @brylie  on https://github.com/apinf/platform/issues/2537#issuecomment-300106617 and https://github.com/apinf/platform/issues/2537#issuecomment-300123997. 

As a mature team, we should clearly understand the basic difference between a `bugfix` and a `hotfix`. 

> The term "hotfix" originally referred to software patches that were applied to "hot" systems; that is, systems which are live, currently running, and in production status rather than development status.
> https://en.wikipedia.org/wiki/Hotfix

I would propose to **NOT FOLLOW** the `hotfix` process for any small bugfixes going forward. A `hotfix` branch should and must be used only against the fixes that are made to specific release tags or branches. Once a `hotfix` is applied for a release, it should be ported back to the `master` and `develop` branches. 

Referring to "**Release tag vs Release branches**". It is good practice to have both, a tag and a branch. A tag might be easy to refer to the release; a release branch comes very handy in case we need to support the release by a `bugfix` or `hotfix` or further development based on customer's needs.  

Last but not the least, referring to this (which I could not ignore and could not help but notice): 

> 
> On a more general level, this issue is an example of assuming things should be different without checking how they actually are. We can certainly improve, but need to understand how things currently work before suggesting changes.
> 
> This is a common pattern for people first joining a team/organization/process (probably related to the idea of bounded rationality), where they suggest the organization should adapt to their previous experience before learning how the process is already working.

Please be advised, suggestions or improvement ideas never come from assumptions but real life experiences. In a team, people join in from different backgrounds and with lot of experience in their own field. A developer's contribution and experience is as important as a QA or Sales guy or DevOps. Nobody tries to fix an already working system.

I understand that that idea of CI and new practices that make software delivery easy (to the customer) are new to this (development) team. It should, at no point be treated as how it has been described in the above comment. 

IMHO and without hurting anyone's feelings, the above comment in itself is an example of bounded rationality and is based completely from within the comfort zone of the author; without having the slightest idea of the value CI and practices relevant to CI bring to a software development team which aims to cater needs to multiple customers in a very short team. 

Comments: @bajiat @brylie @philippeluickx @phanimahesh?

**Comment by mauriciovieira** [comment]
Joining late too...

> - [ ] start using release branches along with release tags

Supposing it would be a bit complicated to implement both at the same time, what would be easier to implement and bring more value as a first step, release branches or release tags?

> I would propose to NOT FOLLOW the hotfix process for any small bugfixes going forward. A hotfix branch should and must be used only against the fixes that are made to specific release tags or branches. Once a hotfix is applied for a release, it should be ported back to the master and develop branches.

OK, so if we agree on this, that means that #2540 should be dropped and instead, it should be a _bugfix_ branch, merging to develop.  I would say we've been doing this way...

**Comment by philippeluickx** [comment]
Would it help if someone would have the explicit role of release manager? Someone who works closely with the product owner (Taija) and is responsible for getting the release out in a decent fashion? That means following a clear process, release notes, communication,...

**Comment by brylie** [comment]
> the above comment in itself is an example of bounded rationality and is based completely from within the comfort zone of the author

The main point of my comment was to say that it is common when new people join our team that they suggest changes immediately. Their perspective is valid, but it is also important that their suggestion take into account current practices. The comment of bounded rationality applies to all of our frames of reference, by nature.

In this case, we are following the Gitflow method to a limited extent. The initial issue seemed to infer that we were not even aware of Gitflow, so I was framing Gitflow as something we want to try.

**I would also avoid this becoming an ideological debate**, going into deep semantics around 'bugfix' 'hotfix'. Lets focus more on the spirit and intention. Those labels aside, the #2540 pull request is intended to be a small, 'patch level' release, so that we can get that fix out to customers before waiting for the full two week sprint cycle or beyond.

**Comment by bajiat** [comment]
I would say it is ok to suggest improvements in the processes when we see the needs to improve regarless whether you are a new or old team member. The suggestions are not personal attacks on any other team members, I assume that process improvement proposals are done for the purpose of improving and for the good / quality of the project. 

I don't think we can come to a conclusion about the process in a Github discussion. Would it be possible for @ashakunt to make a proposal on our process? Let's then have a meeting and make a decision based on that proposal. 

Also, release manager role sounds like a very reasonable idea to me.

**Comment by ashakunt** [comment]
@brylie If we talk about spirit and intention, the we should get rid of all the processes and completely rely on the spirit and intention for all the things in software development. Unfortunately, software development does not really work on spirit and intention. Further, again talking about spirit and intention, please try to see the upside of making sure that a process is followed in a certain fashion and its right meaning. Following half a process is like fixing half a bug. I would not like to get into the discussion of "time to settle and get familiar with existing things", especially because I tried to setup CI and practices for this team exactly a year ago and at that time, it failed miserably. 

As a proposal from @philippeluickx, I can volunteer to act as a release manager unless a suitable person is found. Would like to know if anybody would have an objection to it? 

If #2540 is a fix for customers on top of a previous release, we should move ahead with merging it. If not, lets get it in through `develop` -> `master` -> `specific release branch`

**Comment by brylie** [comment]
> Further, again talking about spirit and intention, please try to see the upside of making sure that a process is followed in a certain fashion and its right meaning.

We are in agreement about the important of common definitions and being consistent with team process. I just don't want to delve so deeply into semantic debates, when all it seems we might need is a nudge here to release more patches. The spirit and intention is to deliver bug fixes to customers in a timely manner.

**Comment by philippeluickx** [comment]
@ashakunt It'd be lovely if you can take that role. @bajiat would that be OK for you? We can define the scope of the role as we go, but I think it would be good if someone with experience can have the mandate to improve our release processes.

**Comment by bajiat** [comment]
yes, I think it would be good if @ashakunt would be willing to take the role of the release and integration manager and improve both processes.

**Comment by phanimahesh** [comment]
For reference and to get things started, here are a few responsibilities of
a release and integration manager.

- Handle creation of release branches when appropriate.
- Review or have someone review every PR into a release branch (backports
and hotfixes) for potential regressions.
- Ensure that we have sufficient tests for any patches being applied.
- Eventually, ensure that every release gets enough test coverage
- Track/ Be aware of all bugs filed against releases, their reproducibility
across releases, and status of fixes.
- Publish signed git tags for releases
- Sign off on release notes.

Primary responsibility of RM is to coordinate and ensure timely delivery of
releases, publishing the releases, and ensuring through testing and other
processes that regressions aren't introduced.

The responsibility of an integration manager would be to setup processes
and ensure compliance to prevent regressions or major unforeseen issues. It
mainly focuses around extensive testing.

**Comment by ashakunt** [comment]
* handle creation of release branches - Must be automated in the Release job in Jenkins
 * backport review for potential regressions - must be handled along with running the actual release set + automated tests for the fix in question
 * ensure sufficient tests for any patches being applied - this is also the responsibility of the development team and the definition of done must be updated accordingly
