### ISSUE TITLE
Allow apinf.io user to see pricing information

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2568]
# User story
As a business owner, I need to communicate the price for API calls over a period to API owners so that they can easily understand the price and quickly judge whether they want to use APInf or not.

Depends on selection made for #2642.

# Goal
* API consumer can see that calling APIs is free and can find a clear call to action: e.g. browse APIs.
* API owners can see the free tier and paid tier and can find a clear call to action: e.g. add API.
* Pricing information is only shown on apinf.io. Refer to #2642 for more information on options.

# Wireframes
Pricing option appears in front page in between Latest APIs section and Contact form section.
Pricing section can be enabled to appear in front page via settings.
The free and paid schemes appear in the pricing section.
Schemes can be customized from pricing module under settings.
For Free scheme, the CTA is Browse APIs (to hook newcomers in APInf to look through the catalog page. when they wish to bookmark or get API key, we prompt them to register/sign in.
For paid scheme, the CTA is to sign up to add API.
![pricing](https://user-images.githubusercontent.com/17976243/26968396-8e63c5ee-4d0a-11e7-975a-97b90da313a9.png)

**Comment by Nazarah** [comment]
interested.

**Comment by Nazarah** [comment]
@bajiat apart from estimated API call amount, what are the possible fields that should be included in the price calculator?

**Comment by Nazarah** [comment]
@bajiat Does pricing need to be in the front page? I am looking at this example here which navigates users to a separate pricing page where all pricing offers are explained in details with a calculator to sum up the cost as per your need. Since we are allowing customer to plan their pricing scheme, I recommend to have something similar. We can always have a placeholder in front page container which would hook user to navigate towards this pricing page

**Comment by Nazarah** [comment]
I have a few questions that need answer:

1. Do you want the pricing option to be in platform front page (apinf.io) or in apinf's organization website (apinf.org)
2. Although we would have cost calculator to customize enterprise (organization scheme), do you want to add a monthly and yearly payment system? In this way, with the yearly scheme chosen, you can offer some discount in the overall price

**Comment by bajiat** [comment]
Let's opt for the simplest possible solution to show a pricing table without calculators (free tier and price per calls when free tier is exceeded), but the pricing needs to be configurable so that it can be left out in deployments where it should not be included.

**Comment by bajiat** [comment]
Is it enough if branding has a field for custom HTML for now for us to be able to show pricing information on the front page? Other deployments could use it for other purposes (e.g. their news on front page).

**Comment by bajiat** [comment]
@Nazarah Please create an issue for the wireframe so that you can close it when the wireframe has been added to the  main issue. I will move this issue back to the Ready column.

**Comment by Nazarah** [comment]
On it.

**Comment by 55** [comment]
Based on the wireframes, here is the HTML/CSS code to implement proposed elements for the home page, this will be pasted into the `Custom HTML block` field at branding page:

```HTML
<div class="container" id="custom-block">
  <div class="text-center">
    <h2 style="margin-top:2em;">Start using APIs for free</h2>
    <p style="font-size:16px; margin-top:1em; margin-bottom:1em;">
      Get access to hundreds of APIs and start using the in no times.
      <br>
      Get community collaboration to build your services
    </p>
    <a class="btn btn-primary btn-lg" href="/apis">
      Browse APIs
    </a>
  </div>
  <h2 class="text-center" style="margin-top:2em;">Manage your own APIs</h2>
  <div style="max-width:600px; margin: 2em auto 0 auto; font-size: 16px; text-align: center;">
    <table class="table" style="margin-bottom:0.5em;">
      <thead>
        <tr>
          <th style="text-align: center; font-weight: 400; border: none;">
            API calls per day
          </th>
          <th style="text-align: center; font-weight: 400; border: none;">
            Price
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            0 - 30,000
          </td>
          <td style="font-weight: 600;">
            FREE
          </td>
        </tr>
        <tr>
          <td>
            30,000+<sup style="font-size: 0.6em; vertical-align: top; position: relative; top: 0.5em;">*</sup>
          </td>
          <td>
            0.5¢/1000
          </td>
        </tr>
      </tbody>
    </table>
    <p style="font-size:11px;">
      *
      with up to 10Gb/day with 0.05€ per every additional gigabyte of usage.
    </p>
    <p class="text-center" style="font-size:16px; margin-top:1em;">
      No contract and credit card needed.
    </p>
    <a style="margin-top:1em;" class="btn btn-primary btn-lg" href="/sign-up">
      Sign up to add API
    </a>
  </div>
</div>
```

**Comment by Nazarah** [comment]
All though the issue is closed, (for reference) I am adding the wireframes that I designed for future implementation of Saas monetization:

**Pricing Module**
1.Pricing module appears as a separate menu in site configuration.
![pricing4](https://user-images.githubusercontent.com/17976243/26969034-f3630084-4d0c-11e7-9096-1effdd902a92.png)

The reason for this is to keep the pricing module only for APInf instance. 
If anyone else wishes to use this, they can fork the code
![image](https://user-images.githubusercontent.com/17976243/26968554-159673ea-4d0b-11e7-9647-72ac1cefaa54.png)

2. The module can be **enabled** to appear on front page by checking the check box.
**currency** can be selected from the related dropmenu and an option to name the module in front page is also given.
![image](https://user-images.githubusercontent.com/17976243/26968699-a00b0220-4d0b-11e7-94be-95c8b8dcda9b.png)

3. Pricing schemes can be added by clicking the **Add New Scheme** button
On clicking a button additional fields to define a scheme appears.
Each scheme has **title**, **type**, **description**, **additional condition** and a button to **add scheme features**.
Title and type dropmenu are mandatory.
Information given in these fields appear in the front page (please refer to comment 1 image)
![image](https://user-images.githubusercontent.com/17976243/26968827-1ead1b18-4d0c-11e7-9ded-e06c6d446f50.png)
Scheme can have two types: **Free - Daily** and **Paid -Daily**
For free scheme, no additional field to quote price appears.
An added scheme can be deleted by clicking the delete icon

4. For a paid scheme, additional fields to quote price appears. They are:
* **Number. of Free Calls**
* **Number. of Next Paid Calls.**
* 2 fields to quote **Price** in defined currency per **Number of Calls**.

Scheme features for a specific scheme by clicking **Add Scheme Feature** button.
They can be deleted if needed by clicking associlated delete button.
Also **additional condition** for a scheme can be added via respective text field.
(please refer to the image in comment 1 to see how the highlighted information appears)
![image](https://user-images.githubusercontent.com/17976243/26969167-75bd55b6-4d0d-11e7-9351-5e07de2b0de1.png)

5. On clicking Save, the price module would be saved and appear in front page.

P.S. For cautionary purpose, a check can be added to see if user tries to add more than 1 free scheme. attempting to do so would alert the user and the action would be cancelled.
