### ISSUE TITLE
Footer code doesn't work properly for all pages

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#2601]
After saving footer code `(console.log('footer code');)`, it seems to work correctly on all pages. However, when navigating from the Organizations page to the Add API page, the footer code does not seem to evaluate:

![peek 2017-05-03 15-09](https://cloud.githubusercontent.com/assets/17307/25659932/a97f070e-3012-11e7-9e5f-0e65aac06163.gif)

### Steps

1. Open Console DevTools
2. Go to Branding settings and fill up value in field "Footer code"
3. Navigate from "Organizations" to "Add API"

### Expected
- Footer code executing

### Found
- Footer code didn't execute

**Comment by 55** [comment]
@marla-singer @brylie in my opinion, current solution should be revised. 

Together with @philippeluickx we found out that, for example Google Analytics (using their debug mode), needs to run once, other possible services maybe have different behavior and requirements, and we need to find a generic solution to support all or at least the most cases (e.g. what we do if admin adds a HTML code, expecting to see it in a footer?).

Current solution doesn't support direct access with URL and at least one more case of changing routes (from organizations catalog to single organization).

To cover case with direct access, we can do something like this:

```
Template.masterLayout.onCreated(function () {
...
  // Run this each time something changes
  instance.autorun(() => {
    // Check for template subscriptions
    if (instance.subscriptionsReady) {
      // Get Branding collection content
      const branding = Branding.findOne();
      // Check if Branding collection and footerCode are available
      if (branding && branding.footerCode) {
        // Set the footerCode
        const footerCode = branding.footerCode;
        // eslint-disable-next-line
        eval(footerCode);
      }
    }
  });
});
```
but still overall solution looks not right to me. 

I suggest to try find a way to use OKGrow:analytics (or similar packages) and drop a support of footer code, rather than fixing existing implementation.

**Comment by brylie** [comment]
> I suggest to try find a way to use OKGrow:analytics (or similar packages) and drop a support of footer code, rather than fixing existing implementation.

One limitation regarding the OKGrow:Analytics package, was that [it was not obvious how to update analytics settings at runtime](https://github.com/apinf/platform/issues/2288#issuecomment-297651261). The OKGrow:analytics package [expects analytics configuration to be passed in when Meteor is started, via a JSON file](https://github.com/okgrow/analytics#configuration).

For any analytics solution, we need to figure out how to retrieve the analytics settings dynamically, so that admin users can manage the settings via the user interface.

**Comment by 55** [comment]
> In version 3.X of this package, the automatic page view tracking is handled by our new router-agnostic [`@okgrow/auto-analytics`](https://www.npmjs.com/package/@okgrow/auto-analytics) NPM package, which can be used by any JavaScript application whether using Meteor or not. This package adds automatic user identification by using hooks in the Meteor accounts package and building on Segment.io's analytics package through the` @okgrow/auto-analytics` package.

It can be configured this way:

```
import OKGAnalytics, { analytics } from '@okgrow/auto-analytics';
 
const settings = {
  // Add your analytics tracking ids here (remove this line before running)
  "Google Analytics" : {"trackingId": "Your tracking ID"},
  "Amplitude"        : {"apiKey": "..."},
  "Chartbeat"        : {"uid": "..."},
  "comScore"         : {"c2": "..."},
  "HubSpot"          : {"portalId": "..."},
  "Intercom"         : {"appId": "..."},
  "Keen IO"          : {"projectId": "...", "writeKey": "..."},
  "KISSmetrics"      : {"apiKey": "..."},
  "Mixpanel"         : {"token":  "...", "people": true},
  "Quantcast"        : {"pCode": "..."},
  "Segment.io"       : {"apiKey": "..."}
};
 
OKGAnalytics(settings);
```

@brylie What do you think? Worth a shot?

**Comment by brylie** [comment]
> @brylie What do you think? Worth a shot?
Looks good! :smile:

**Comment by philippeluickx** [comment]
@55 thanks for digging further into it. Seems like you found a good and elegant solution!
Too bad for hotjar then, but having GA will be a big win already.

**Comment by preriasusi** [comment]
@55 Is this still valid?

**Comment by 55** [comment]
@preriasusi nope.
