### ISSUE TITLE
Issue with getting API key for new API

### ISSUE THREAD

**Issue by wuder4** [apinf/platform#2606]
I followed the steps on "test cases nightly apinf" doc. On part 7.Dashboard it asks you to make API and click get API key. I cant find this button anywhere.

Steps to reproduce:
1. create new API
2. go to that API in the catalog

Expected result:
3.1. find button with "get API key" on the page
4.1. continue testing

Real result:
3.2. button cant be found anywhere

This was tested on windows 8.1 and latest chrome version.

**Comment by Nazarah** [comment]
Hi @wuder4 
Thanks for taking interest in APinf.
As you are creating an API, you become the owner of the API.
So it is owner's decision whether or not to provide an API key to the consumers of the API that you created.
In order to provide your API with an API Key, you need to connect your API to an available proxy.
This can be accessed from the Proxy tab in API profile.
I am giving an example below.

![proxysetup](https://cloud.githubusercontent.com/assets/17976243/26483988/965ddf4a-41f8-11e7-9eb8-729cf3519eab.gif)


I have an API called Makeup API in apinf.io.
Right now apinf.io has **API Umbrella** set as default proxy.
So when you navigate to proxy tab in API profile, all you need to define your **Proxy Base Path** and **API Base Path**.
If you require your users to use API key to make a call to your API, then keep **Disable API Key Requirement** checkbox unchecked.
After saving the proxy settings, you'll see a "**Get API Key**" button appearing on profile header.
Clicking the button would generate a key for your API to make calls and you would be able to copy this key.
In nightly APInf, there are multiple instances of API umbrella proxy which are configured by site admin.
You can choose one from them to connect your API to the proxy.

Hope this helps. :)

**P.S.** After configuring the proxy, Detail tab in API profile shows information in how to use your API.

**Comment by bajiat** [comment]
@nazarah Thanks for the instructions

@wuder4 This issue would require 1. an update in the  testing documents and 2. considering how to suggest connecting API to a proxy, something like "Congratulations! You have added a new API. Would you like to connect it to a proxy to ....?"

Anyway, I will close this issue as "wontfix".
