### ISSUE TITLE
Implement server-aggregated aver. response time chart

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2636]
To get the server-aggregated dashboard kickstarted, we will start with two charts: number of calls and response times charts. This task is about implementing the Average response times chart.

# Goal
* Show average response times (from API Umbrella) for the selected API backend 
* Any aggregation is performed on the server side for the current timeframe
* Chart is created based on the server-aggregated data
* Simplest possible first implementation: week is the default timeframe 
* Chart is tested with a heavy-set of data for calls, utilise for example a script that automatically makes calls to one API to different endpoints

# Wireframes
To go to the chart for Response time chart, User needs to click on any place of the overview pane (API name dropdown, metrics card).
![image](https://user-images.githubusercontent.com/17976243/27372433-502d50bc-566d-11e7-91c9-3070c561fd64.png)
On click, user is navigated to a new page, where s/he can see the average response time chart.
![image](https://user-images.githubusercontent.com/17976243/27372536-a5765b36-566d-11e7-8db9-a7746068d958.png)
A line chart should be used to represent the average response time like [this example](http://nvd3.org/examples/lineWithFocus.html)
The x-Axis should indicate the timeline in weekly basis (Last 7 days)
The y- axis should indicate Average Response Time in mili seconds.
At the bottom of the chart a text in light font should indicate average response time is calculated as a median value.
>*Average response time calculated as a median value.

**Comment by bajiat** [comment]
@marla-singer Would you be interested to work with the chart aggregations?

**Comment by marla-singer** [comment]
@bajiat Self-assigned

**Comment by brylie** [comment]
> Owner can see figures for following items for the selected API backend
>    - Average response time

We might consider showing the **median** response time, rather than the **mean**.

# Rationale
> for skewed distributions, the mean is not necessarily the same as the middle value (median), or the most likely value (mode).
>
> Wikipedia: [Mean -- Statistical location](https://en.wikipedia.org/wiki/Mean#Statistical_location)

The *response times* data is positively skewed, so it leans to the left:

![screenshot_20170620_132340](https://user-images.githubusercontent.com/17307/27328698-affba302-55bb-11e7-99af-d36f3b3a10db.png)

When a data set is skewed, the *mean* is no longer a good representation of the 'middle' of the data, since it is susceptible to extreme values (outliers):

![comparison of mean, median, and mode](https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Comparison_mean_median_mode.svg/512px-Comparison_mean_median_mode.svg.png)

**Comment by Nazarah** [comment]
Ok with the median value of the response time.
See if the visualization can be implemented with line charts from NVD3 library.
Make sure we are showing axis information and units visibly accurately in any charts that would be included.

**Comment by brylie** [comment]
@Nazarah @marla-singer: Here is an updated wireframe for the Dashboard charts showing bar charts for the daily values:

![screenshot_20170620_151608](https://user-images.githubusercontent.com/17307/27332690-94bb86d8-55cb-11e7-8384-2e417a7b0f38.png)

**Comment by brylie** [comment]
For comparison, here is the previous wireframe using (spark)line charts:

![screenshot_20170615_172316](https://user-images.githubusercontent.com/17307/27332724-b8399fdc-55cb-11e7-9dfe-4032ced42b3a.png)

**Comment by sa1** [comment]
While the median does a good job of not being influenced by outliers, sometimes information about the outliers is also helpful in identifying real but occasional issues. One way of doing this is to also show the user 90th or 95th percentile response times along with the median.

> Chart is tested with a heavy-set of data for calls, utilise for example a script that automatically makes calls to one API to different endpoints

One needs to be slightly careful here. 
There are two scenarios: when an API is under heavy load and when its in normal operation.

When an API is under heavy load, requests are queued one after the other. So, even if a single request takes a long time to process, it affects response times of all other requests that are queued after it, i.e the response time of the outlier gets added to response times of requests after it.
In this case, median response times would be very close to the extreme response times.

Under normal operation, response times of outliers should not affect response times of other requests.

So, when this is tested in the future, one could make a note that both modes of operation need to be tested, and come to a decision of what information is relevant in each case.

**Comment by Nazarah** [comment]
@55 and I concluded our user interviews with two versions of the dashboard prototypes. 
The scripts can be found [here](https://github.com/apinf/docs/blob/master/docs/design/dashboard/Prototype-Testing-Asim.md), [here](https://github.com/apinf/docs/blob/master/docs/design/dashboard/Prototype-Testing-Jarkko.md) and [here](https://github.com/apinf/docs/blob/master/docs/design/dashboard/Prototype-Testing-Vesa.md)

After analyzing the feedback from all interviewees, we came out with the following findings.
- User's are now looking for means to monitor their API's status. The APIs differ in their functionalities. So the overview should focus rather on notifying the status of the APIs listed, not for the purpose of comparison.
- Users prefer numbers and percentiles to understand what is the current situation with a specific metrics (No. of calls, Average Response Time and Users) and how the trend has been changed (increased/decreased) over time. Associating trendlines is not mandatory here.
- Users emphasize on readability and focusing their attention so that they can comprehend what is going on and what needs their attention. Associating trendlines with numerics and percentiles for every metrics side by side makes it difficult for them to understand how these elements relate with each other. Also there are possibilities of cluttering too many elements which might not be helpful for responsive design.
- Users prefer Numbers and percentiles appearing in Big fonts for related metrics. Also they prefer percentiles appearing in red/green text indicating their trend changes in context with the metric types.

So based on the feedback from @ashakunt @kyyberi and @preriasusi and our own analysis, we have decided to go with the originally proposed wireframes for this iteration of dashboard implementation.
As soon as we have them functioning, we will conduct user interviews with the above participants as well as possible ones outside APInf premise. I'll add the wireframes in related issues with descriptions.

@ccsr @bajiat looking for your feedback here.

**Comment by kyyberi** [comment]
I agree with @Nazarah. Lets go forward. Both of the wireframes contain excess element IMHO. For example the bookmakrks count (I assume it's that) and rating is not needed in overview of how our APIs are performing. Those are related to onboarding success. The dashboard discussed here is not focused on that. Onboarding tracking will come to your desk soon, but these who are separate items at least for now.

**Comment by brylie** [comment]
> While the median does a good job of not being influenced by outliers, sometimes information about the outliers is also helpful in identifying real but occasional issues. One way of doing this is to also show the user 90th or 95th percentile response times along with the median.

Good point. Stephen Few designed a chart, called a Bullet Chart, that might be useful to show this information in a compact form. An example of the Bullet Chart can be seen on the cover of Information Dashboard Design:

![infodash_design](https://user-images.githubusercontent.com/17307/27426268-be792ac4-5743-11e7-85e6-ee70ae217174.jpg)


> ![Bullet Chart from Information Dashboard Design](http://www.doctormetrics.com/wp-content/uploads/2015/05/BulletGraph-Few.png)
>
> More information: Information Dashboard Design: Designing Bullet Graphs (chapter 9)

NVD3 provides a [bullet chart that we can use](http://nvd3.org/examples/bullet.html), if desired.

**Comment by brylie** [comment]
Here is a Bullet Chart mockup for *response time* data:

![screenshot_20170622_124547](https://user-images.githubusercontent.com/17307/27427748-c7b0b6a2-5748-11e7-9175-600344236abc.png)

**Comment by brylie** [comment]
We might even be able to encode qualitative information using color, such as the whether the current value is:

- poor
- medium
- good

![screenshot_20170622_125309](https://user-images.githubusercontent.com/17307/27428120-c2f2dd88-5749-11e7-87a6-18b86f059402.png)

**Comment by brylie** [comment]
Here is a slightly wider view of how we *might* be able to integrate the large number displays, trend arrow/percentages, and bullet chart closely together:

![screenshot_20170622_141107](https://user-images.githubusercontent.com/17307/27431321-d15b9f26-5754-11e7-859e-f67f67ec145d.png)

**Comment by brylie** [comment]
@preriasusi and I have seen line charts fail to render when there is one one aggregated value. E.g. when rendering a chart with values aggregated by month and where all of the data are within the range of only one month, there will be only one aggregated value. We may need to consider a safe default, so the line chart has a high likelihood of rendering.

# Line chart with only one aggregated value
In the following chart, the granularity is set to 'month' so all data are aggregated to a single value. Hence, the line chart fails to render.
![screenshot_20170731_110540](https://user-images.githubusercontent.com/17307/28768420-34f9a07e-75e0-11e7-9eee-6b15228a81a2.png)

# Line chart with multiple aggregated values
In the following chart, the 'granularity' is set to daily, so the chart renders.

![screenshot_20170731_110732](https://user-images.githubusercontent.com/17307/28768481-7614847a-75e0-11e7-8de1-8525eaea26b5.png)
