### ISSUE TITLE
Allow apinf.io admin to add pricing information

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2642]
# User story

As a business owner, I need to determine the  the price for API calls over a period so that I can communicate it to the  API owners.

# Options
* **Option 1**: Branding page contains a text box for adding HTML.  This section will be used for displaying pricing text, table and buttons in apinf.io. In other deployments admin can use the text box e.g. for news or decide not to use it at all.
* **Option 2**: Pricing is available as a menu item in the settings menu. This is primarily intended for apinf.io and should be disabled from any other deployments.

Refer to the wireframe for the options. Goals to be added based on the decision on the options.

Related to #2568.

**Comment by Nazarah** [comment]
Although the issue is closed, I am adding the wireframes for future reference when Saas Monetization is implemented.

**Pricing Module**
1.Pricing module appears as a separate menu in site configuration.
![pricing4](https://user-images.githubusercontent.com/17976243/26969034-f3630084-4d0c-11e7-9096-1effdd902a92.png)

The reason for this is to keep the pricing module only for APInf instance. 
If anyone else wishes to use this, they can fork the code
![image](https://user-images.githubusercontent.com/17976243/26968554-159673ea-4d0b-11e7-9647-72ac1cefaa54.png)

2. The module can be **enabled** to appear on front page by checking the check box.
**currency** can be selected from the related dropmenu and an option to name the module in front page is also given.
![image](https://user-images.githubusercontent.com/17976243/26968699-a00b0220-4d0b-11e7-94be-95c8b8dcda9b.png)

3. Pricing schemes can be added by clicking the **Add New Scheme** button
On clicking a button additional fields to define a scheme appears.
Each scheme has **title**, **type**, **description**, **additional condition** and a button to **add scheme features**.
Title and type dropmenu are mandatory.
Information given in these fields appear in the front page (please refer to comment 1 image)
![image](https://user-images.githubusercontent.com/17976243/26968827-1ead1b18-4d0c-11e7-9ded-e06c6d446f50.png)
Scheme can have two types: **Free - Daily** and **Paid -Daily**
For free scheme, no additional field to quote price appears.
An added scheme can be deleted by clicking the delete icon

4. For a paid scheme, additional fields to quote price appears. They are:
* **Number. of Free Calls**
* **Number. of Next Paid Calls.**
* 2 fields to quote **Price** in defined currency per **Number of Calls**.

Scheme features for a specific scheme by clicking **Add Scheme Feature** button.
They can be deleted if needed by clicking associlated delete button.
Also **additional condition** for a scheme can be added via respective text field.
(please refer to the image in comment 1 to see how the highlighted information appears)
![image](https://user-images.githubusercontent.com/17976243/26969167-75bd55b6-4d0d-11e7-9351-5e07de2b0de1.png)

5. On clicking Save, the price module would be saved and appear in front page.

P.S. For cautionary purpose, a check can be added to see if user tries to add more than 1 free scheme. attempting to do so would alert the user and the action would be cancelled.

**Comment by Nazarah** [comment]
![image](https://user-images.githubusercontent.com/17976243/26969535-bf5ad3b4-4d0e-11e7-9937-d444ead97ac2.png)
an advanced option to customize a paid scheme is to add several pricing option.
(e.g. after  free 30000 calls, next 500000 calls have a rate of 20 cents per 1000 calls.
and afterwards, next 1000000 calls have  a rate of 15 cents per 2000 calls.)
added pricing options can be deleted as well.

**Comment by brylie** [comment]
@Nazarah where can I refer to those wireframes later? Are they in our docs repository somewhere?

**Comment by Nazarah** [comment]
@brylie I'll upload them in Doc repository under a new folder called monetization.

**Comment by mauriciovieira** [comment]
@Nazarah I am reading about FIWARE. So this commit https://github.com/apinf/docs/commit/b946c415f36bebca8a608290c34c8cd2f50385ad was the commit?

**Comment by Nazarah** [comment]
@mauriciovieira you are absolutely correct!! :)
