### ISSUE TITLE
Implement usage figures for single API

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2644]
# Goal
* Owner can see figures for following items for the selected API backend 
  * Number of calls
  * Average response time
  * Unique users
* If any aggregation is needed for the figures, it is performed on the server side for the current timeframe
* Simplest possible first implementation: week is the default timeframe 
* Implementation is tested with a heavy-set of data for calls, utilise for example a script that automatically makes calls to one API to different endpoints

## Reference
Wireframes: https://github.com/apinf/docs/blob/master/docs/Wireframes/Dashboard/New%20Dashboard/apinf-dashboard-details-simple.pdf

**Comment by bajiat** [comment]
@marla-singer Would you be interested in this task? @55 has promised to co-pilot.

**Comment by marla-singer** [comment]
@bajiat Self-assigned

**Comment by brylie** [comment]
> Owner can see figures for following items for the selected API backend
>    - Average response time

We might consider showing the **median** response time, rather than the **mean**.

# Rationale
The *response times* data is positively skewed, so it leans to the left:

![screenshot_20170620_132340](https://user-images.githubusercontent.com/17307/27328698-affba302-55bb-11e7-99af-d36f3b3a10db.png)

When a data set is skewed, the *mean* is no longer a good representation of the 'middle' of the data, since it is susceptible to extreme values (outliers):

![comparison of mean, median, and mode](https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Comparison_mean_median_mode.svg/512px-Comparison_mean_median_mode.svg.png)

**Comment by Nazarah** [comment]
@brylie @marla-singer can u have a look and see if NVD3 has line graphs instead of bar charts to show the average response time.
There is no problem with going with median response time. In my knowledge, we have the same concept in the current dashboard. The goal should be to display accurate and updated data no matter what cleaning or processing formula is being used.

**Comment by marla-singer** [comment]
@Nazarah This task doesn't need any chart. Please duplicate your comment in reference issue

**Comment by Nazarah** [comment]
@marla-singer I have added the comment in the referenced issues as well. 
however as I saw there is a wireframe needed label in this issue, I posted the comment here.
To avoid confusions, I am removing that label from this issue.
