### ISSUE TITLE
Pagination or Lazy loading in Dashboard view

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2741]
# Description
pagination (or lazy loading) should be used when user has large number of APIs to view.
The grouping of **My APIs**, **My Managed APIs** and **Other APIs** should be considered while implementation

# User Story
> "As an   API owner I need to be able to view all my APIs if they do not fit in the  primary view."

# Definition of Done
TBD

# Wireframe
**pagination**
![dashboard1_pagination](https://user-images.githubusercontent.com/17976243/28572779-132cb884-7151-11e7-90f4-6bcb4476dec9.png)

**Lazy Load**
![dashboard1_admin](https://user-images.githubusercontent.com/17976243/28572793-2482b2aa-7151-11e7-8f9e-0e24e9795020.png)

**Comment by marla-singer** [comment]
@Nazarah @bajiat @brylie I suggest reconsidering the question about pagination and lazy loading on the Dashboard page.

**Why do we need pagination?** 

First at all is for server side. A server pagination needs if it is hard (or slow or expensive) to get all 100 items from a server at one time. In this case, there send a request to get first 20 items and after that get next 20 items and other next ones and etc. 

In our case, we don't need a server pagination because we get all data at one time. It is our new principal, we're getting aggregated data.

The second one is pagination for client side. But I'm wondering why do we need lazy loading? How many APIs would a user have that s/he would need paginating them? 50 items? 100 items? But it is unbelievable case for ordinary user

On the other hand, Admin User has an access to all connected APIs and the count of them can be 50 or 100 items. But we have a sort feature, a filter feature, groups (My APIs, Managed APIs, Other APIs). Do we really need a pagination?

**Comment by brylie** [comment]
This seems like a common pattern. 

My intuition says to wait until we need it. That way we have a bit more time to get the initial iteration done, and think about how pagination would work.

**Comment by Nazarah** [comment]
@marla-singer I leave it on you to decide in terms of technical aspects and the optimal solution. Just keep in mind that separating APIs based on your own, the ones you manage and others (if you are a site admin) has been preferred. I know its kind of unrealistic for the time being, but in future APInf might have 100s APIs. Some of them are added by site admin, some s/he manages as part of an organization and s/he can access others because of his role privilege. Whatever the case is, choose the implementation that is optimal as well as aesthetic for both the service and UI.

**Comment by preriasusi** [comment]
@marla-singer Is this valid still?

**Comment by Nazarah** [comment]
@preriasusi We'll have a new look to Dashboard starting from EMQ.
There we'll consider about using pagination or lazy loading.

**Comment by 55** [comment]
Since we don't know how exactly people are going to use our dashboard, let's not make any decisions or plans right now. My vote is for preloading, where user sees some APIs and others load in the background. I move it to icebox, and let's go back it once it's relevant.
