### ISSUE TITLE
Show status of an endpoint in an API

### ISSUE THREAD

**Issue by Nazarah** [apinf/platform#2743]
# Description
API owner should be able to determine if her/his API endpoint is down from a glance.
If there is multiple endpoints of an API, user should have the option to select one endpoint to monitor.

# User story
> "As an API owner, I want to know API endpoint Status, so that I can know if my API is Live or Down."

# Definition of Done
- [ ] both in  list and detailed view the status of the API endpoint should appear
- [ ] If an API has multiple endpoints, user would be prompted to select one from them
- [ ] Live/Down (response visualization of the end point)
**Open question:**: how to determine? PING? HTTP Request?

# Wireframe
![image](https://user-images.githubusercontent.com/17976243/28617128-cfad6df8-7207-11e7-83e8-e94b84d843b3.png)

When endpoint is down
Text: "Endpoint: DOWN"; font size: 13, color: #b94848
on accordian: fontsize: 9px

**Comment by marla-singer** [comment]
Another open question:
- Which status will indicate as down? 4XX or 5XX

**Comment by Nazarah** [comment]
@marla-singer most logical solution would be to use 5XX as Down condition. This is the problem from the server's side if I am correct.

**Comment by Nazarah** [comment]
@phanimahesh I guess we don't have option to determine endpoint condition of APIs connected to MQTT broker. If you agree, then I'd remove EMQ label from this issue.

**Comment by phanimahesh** [comment]
In a sense, yes. "API endpoint" in the MQTT broker doesn't exist as we defined it. Any recoverable failures are automatically handled, and any unrecoverable failure impacts every single "api" hosted on the broker.

Also since HTTP follows a request response cycle, error responses are defined in the spec. In MQTT, there is no request response cycle defined in the spec, and as such HTTP style errors don't exist. Under normal operation, most messages would be transmitted in QoS 0 which would fire and forget, by design, so not being able to deliver the message is normal.

Please remove EMQ label from this issue.
