### ISSUE TITLE
Add OpenAPI designer iframe integration

### ISSUE THREAD

**Issue by xylix** [apinf/platform#2780]
Wireframes available [here](https://github.com/apinf/platform/issues/1998).

Example OpenAPI designer in iframe with authtoken sending support available [here](https://dev.openapi.design/iframe.html).

**Comment by marla-singer** [comment]
@xylix Sorry, I don't need a demo of Editor work. I need an example how to display this iframe.

**Comment by xylix** [comment]
You should look at the source for an example implementation [e.g. here](view-source:https://dev.openapi.design/iframe.html)

**Comment by marla-singer** [comment]
@xylir Umh, Excuse me, but like a user of your package, I don't want to waste my time and **look at the source for an example implementation**. You must provide documentation about your package. Please do.

**Comment by xylix** [comment]
@marla-singer Okay sorry. Me and @tulir already  ended our workday so we will make you some proper documentation by monday.

**Comment by tulir** [comment]
[Here](https://github.com/apinf/openapi-designer/blob/feature/integration-docs/docs/INTEGRATION.md) are some initial docs.

**Comment by marla-singer** [comment]
@xylix @tulir Now it looks better, thanks

**Comment by marla-singer** [comment]
@xylix @tulir While I'm integrating OpenAPI designer, I found the next points to improve:
1. Don't show DEBUG data in the DevTools console. I think Aurelia must have "production" setup where debug data doesn't display.
2. Clean up all `console.log` in your project. DevTools console has the next output:
```js
Object {debug: true, initImmediate: true, ns: Array(1), defaultNS: Array(1), fallbackLng: Array(1)…}
```
3. And other warnings(errors) like
```
i18next::translator: missingKey en translation form.header.helpText form.header.helpText
```

**Comment by xylix** [comment]
Yes aurelia has a production mode. The current version at openapi.design hasn't been built with it, but maybe we should do that. I'll look at this more tomorrow.

**Comment by mauriciovieira** [comment]
In my opinion, for the best (APInf Platform and other people) developer experience, this integration should be a pluggable library, not iframe. 

See for instance, our current [swagger_ui integration](https://github.com/apinf/platform/tree/fcde92f819dd5138db35299e3b0ef4e35859bba5/api_docs/client/swagger_ui). We had to copy the generated swagger_ui library into our code because they don't provide a plugabble npm package.

The ideal solution for was would be a meteor package containing openapi.designer and we just had to

```
import { openApiDesigner } from 'meteor/apinf:openApiDesigner';
```

**Comment by xylix** [comment]
@mauriciovieira I can see your point. I haven't created any meteor packages so I don't know if bundling an aurelia app into a meteor package would be a good idea (thinking about the work required and the site's performance here). @brylie Any input on this?

**Comment by mauriciovieira** [comment]
@xylix we should package at least as a npm package, so that other people can profit from our open source work.

In this case, something like 

```
import { openApiDesigner } from 'open-api-designer';
```

should work after openApiDesigner is published in https://www.npmjs.com/package/open-api-designer and properly installed.

I don't have aurelia experience, but can surely help.

**Comment by Nazarah** [comment]
@kyyberi you had your concerns about integrating OpenAPI Designer in APInf as iframe. Can you please share your thoughts with us?

**Comment by marla-singer** [comment]
@xylix @tulir As the first step I display OpenAPI designer into the platform. The next step is to provide user ID and Token. It looks not a trivial task and I'd like to do it as a separate task. 

By the way, if I provide the faked ID and Token and click on "OpenAPI Space" button on the editor then it displays me Log in form. So how providing user ID and Token will help you if an user needs to entire credentials again? :thinking:

**Comment by xylix** [comment]
@marla-singer I think splitting it into separate tasks is a good idea.

About the faked credentials, the designer is supposed to listen and put the credentials into the correct place, and then when user clicks "OpenAPI space" button they are supposed to  already be logged in. This sounds like a bug in space's code, I'll look at it tomorrow.

**Comment by tulir** [comment]
If the parent window gives a correct user ID and auth token, the designer will log into space using them the first time the user tries to upload a document. A fake/invalid auth token currently just fails silently, because the user shouldn't be aware of the extra steps (they've already logged into APInf platform).

**Comment by marla-singer** [comment]
@xylix I think it happens because of Meteor. Will try to fix it
