### ISSUE TITLE
Edit API name not updated in browser URL

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#2805]
# Steps     
1.Visit https://staging.apinf.io   (v 0.48.0)  
2.Login  
3.Add API  (eg: Test-API-abc)
4.Go to above added API 'Settings'  
5.Edit the name of API (eg.Test-API-xyz)
6.Click on 'Save'    
7.Go to above 'API' profile from catalog    

# Expected Result  
Successful in edit-save name of API and the updated name shown in browser URL 

# Actual Result    
- Successful edit-save name of API but not updated in browser URL.Shows the previous name    
- Shows updated API name in Catalog,Profile and Settings views though     
 
# Browsers    
Chrome  v 52.0.2743.116 (64-bit)   
 
# Operating system     
Ubuntu 16.04 LTS     

# Screenshot        
![selection_167](https://user-images.githubusercontent.com/13309358/28908423-3d9f58a6-782c-11e7-93d8-034be198d497.jpg)    

![selection_169](https://user-images.githubusercontent.com/13309358/28908437-54b5efa0-782c-11e7-930d-dd4c1e2bf90b.jpg)

**Comment by bajiat** [comment]
Slug needs to be updated, when  name  is changed.

**Comment by bajiat** [comment]
@brylie Can you find reference code from previous implementation for @saransh-dev ?

**Comment by saransh-dev** [comment]
@bajiat I have found the code where I need to implement and I have implemented it. Now slug will change while API name will change. I am facing following issues:-

1. After update, slug won't change in URL (DT-Comment:- Fixed it)
2. If we update anything in API instead of API's name, it works fine and we can fetch data in onSuccess() inside autoform hook (inside function there is findOne quarry on the basis of _id, it returns undefined). But while update API's name, it does not get data in onSuccess() inside autoform hook (inside function there is findOne quarry on the basis of _id, it returns undefined).
