### ISSUE TITLE
Setup FIWARE Business Ecosystem on a VM

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2811]
In order for us to develop support on FIWARE Business Ecosytem, we need to be able to test API calls and kick the tyres in general.

# Goal
There is a VM, where the Business Ecosystem is running and the APInf team has access to the VM.

# Resources
- [FIWARE BAE Docker image](https://hub.docker.com/r/fiware/business-api-ecosystem/)

**Comment by bajiat** [comment]
VM is setup already

**Comment by brylie** [comment]
For this task we need the following:

- OAUTH2_CLIENT_ID: Client id given by the FIWARE IdM for the application
- OAUTH2_CLIENT_SECRET: Client secret given by the FIWARE IdM for the application
- PAYPAL_CLIENT_ID: Client id given by PayPal for the application in order to charge customers (Sanbox accounts are allowed)
- PAYPAL_CLIENT_SECRET: Client secret given by PayPal for the application in order to charge customers (Sanbox accounts are allowed)
- EMAIL_USER: User of the email account to be used for notifications
- EMAIL_PASSWD: Password of the email account to be used for notifications
-EMAIL_SERVER: SMTP server host of the email account to be used for notifications
- EMAIL_SERVER_PORT: SMTP server port of the email account to be used for notifications


So, we may need to also [install the FIWARE IdM](http://fiware-idm.readthedocs.io/en/latest/admin_guide.html).

**Comment by ccsr** [comment]
Lets postpone this as we have quite a many burning issues. Please put it in Icebox

**Comment by ccsr** [comment]
Moved to Icebox

**Comment by ilarimikkonen** [comment]
done?
