### ISSUE TITLE
Add a setting for "Only admins can add organizations"

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2840]
# Description
After task #2839 is completed, any logged-in user is able to create a new organizations. In some deployments, it maybe necessary to be able to configure this and allow only admins to create new organizations. As there is a setting for "Only platform administrators are allowed to add new APIs", there should be a setting for "Only platform administrators are allowed to add new organizations".

# Goal
* [ ] It is possible to configure in Settings, whether  any logged-in user or  only platform administrator(s) can add new organization(s)
* [ ] If the restriction "Only platform administrators are allowed to add new organizations" is applied
  * [ ]  the button "Add new organization is available only for admin uses
  * [ ] Only admins  are able to create organizations

Related to #2839

# Wireframe
![image](https://user-images.githubusercontent.com/17976243/29911380-5a02484e-8e36-11e7-99ee-508a86fe62be.png)

**Comment by Nazarah** [comment]
@bajiat wireframe added, please review and provide feedback.

**Comment by bajiat** [comment]
@Nazarah 

Minor comments
* You could also combine the adding apis and adding organizations into one common section
* **Adding** APIs vs. **Add** Organizations
  * Can we use the same verb form in both?
* Only platform administrators are allowed to add new organization
  * It has to be either "to add **a** new organization" or "to add new organization**s**" 
  * Using the plural form would be consistent with the section for adding APIs,

**Comment by Nazarah** [comment]
@bajiat 
>You could also combine the adding apis and adding organizations into one common section
Adding APIs vs. Add Organizations
Can we use the same verb form in both?

We can do that. The section title can be "Adding APIs and Organizations"
Text for API: Only platform administrators are allowed to add new APIs.
Text for organization: Only platform administrators are allowed to add new organizations.

**Comment by Nazarah** [comment]
@bajiat @marla-singer 
Should we have something similar to this since now we are having new access modules and user role privileges?
![addapiadminprivilege2](https://user-images.githubusercontent.com/17976243/29911444-8d75e668-8e36-11e7-8d47-b9b27142cdf9.png)
I am thinking in future there might be new access control and user role privilege settings going to come.
Instead of crowding them Under settings menu, let's have a separate menu for this.
It's easier to manage and is not crowded with irreverent information.
Each time a new access control or privilege is set, it can be added to this menu.

**Comment by marla-singer** [comment]
@Nazarah I like this way :+1:

**Comment by bajiat** [comment]
I also like the basic idea of separating the user privileges from other settings, but I don't like the titles for the radio buttons, since "Add API" does not make sense together with Read privilege. Have already discussed this with @Nazarah.

We also need to have sensible defaults for each setting (something that makes sense for the majority of deployments), which admin can then change.

**Comment by Nazarah** [comment]
@bajiat @marla-singer based on the discussions we are having I prepared this simple wireframe.
![userrolesandprivileges](https://user-images.githubusercontent.com/17976243/30272303-9088830a-96fc-11e7-88d1-dcd72d91b6ef.png)
Here, instead of radio buttons, we'll have checkboxes for "Site Admins" and "General Users" with related privilege options.
The privilege options can be categorized based on the feature they would be controlling (e.g. API, Organization, Settings, etc.)
At any time, new privilege options can be added under each category.
By default we can check all options for users who are site admins.
If more security needs to be ensured for preventing accidental uncheckes, we can make the checked checkboxes for admins inactive.

> but I don't like the titles for the radio buttons, since "Add API" does not make sense together with Read privilege.

The way it is supposed to work with Radio buttons is that if users have **R** access for a privilege (e.g. Add API), they can see the Add API button, it would be inactive for them. They can only click and have the dialog open if they have **W** access for adding API
With radio buttons option, we can be default check W for all privileges for site admin, and then make the controller inactive for accidental clicks.

Looking for your feedback.

**Comment by marla-singer** [comment]
@Nazarah @bajiat 

1. General Users don't have access (and I can't think up case why they can do) to Branding, Proxies, Settings and Privileges pages. It means any user can go to apinf.io, i.e., registers and change Branding color or title, Remove proxy and change github login credentials.

2. Another point I don't like is an opportunity to set "false" for Admin any settings.
If an Admin will set all parameters as "false" then he wouldn't have access to return all stuff back.

Why for? :woman_shrugging: 

I'm leaving the first wireframe 
![joxi_screenshot_1505130242239](https://user-images.githubusercontent.com/20643403/30272969-ac53f954-96ff-11e7-84f0-dafc725efd1b.png)

For the time being it is enough. 
In the future when User roles and privileges will be more than two and will make sense then the owned page will be a good idea.
