### ISSUE TITLE
[Production] API is connected to a proxy, but API URL in Details is not the proxy URL

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#2956]
If an API owner connects an API to proxy, they typically do not want any direct calls to the API. In other words, they do not want to show the backend URL to API consumers at all. This happens for a number of reasons (security, monetization and so on).

I have found at least one API in production (apinf.io), where API is connected to a proxy, but the API base path is still disclosed to users in API profile Details tab.

# Steps to reproduce

1. Log in to apinf.io (e.g. as admin )
2. Go to Catalog
3. Select Pokemon API
4. Check the proxy settings: whether the API is connected to a proxy
5. Check the API URL in the details tab: is it identical to the Proxy base path or the API base path

# Expectation
If API is connected to a proxy, the API URL in Details should be identical to Proxy base path

# Actual result
API is connected to a proxy, but the API URL is the API base path.

# Version
0.47.0

# Screenshot

<img width="527" alt="pokemon_api_url" src="https://user-images.githubusercontent.com/11626388/30599106-2dca39b6-9d64-11e7-8ae9-6478b1fbf921.PNG">

**Comment by marla-singer** [comment]
@bajiat Tested this. It happens because one step of migration is missed when we were integrating MQT proxy. DB schema for Proxy Backend has the additional field `type` and there displays Proxy URL if the type equals "API Umbrella". The APIs are on production site don't have this field.

Three tentative steps to fix:
1. Delete and Publish a Proxy Backend configuration again (via UI) or
2. Create a migration step or
3. Make a simple hook in code

**Comment by bajiat** [comment]
@marla-singer What is you recommendation and why?

**Comment by marla-singer** [comment]
@bajiat I recommendation to create a migration step because it allows keeping our database scheme updated on all sites
