### ISSUE TITLE
Research MongoDB encryption and interaction with Meteor

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3048]
# Description

##   MongoDB encryption
*  Investigate interaction and configuration options when used with Meteor.

**Comment by anarva** [comment]
* MongoDB configuration should bind explicitly all known IP addresses of the application servers and should also require authorization:
https://docs.mongodb.com/v3.2/administration/configuration/#configuration-security

* Instructions on how to deploy a MongoDB replica set (multiple servers) with keyfile access control (x.509 certificate for production environment authentication):
https://docs.mongodb.com/manual/tutorial/deploy-replica-set-with-keyfile-access-control/#deploy-repl-set-with-auth

* Connecting Meteor to MongoDB requiring a x.509 certificate (Meteor version  > 1.4) : https://stackoverflow.com/questions/34383970/meteor-js-connection-to-mongo-using-x509-certificate-auth

* Encryption on the database file storage level (= at rest) is an enterprise version feature requiring a commercial license since MongoDB v3.2. It has compliance with security and privacy standards, including HIPAA, PCI-DSS, and FERPA. https://docs.mongodb.com/manual/core/security-encryption-at-rest/

**Comment by anarva** [comment]
"MongoDB Security and encryption.odt" ready for review on separately disclosed option.
