### ISSUE TITLE
Dashboard: Store ElasticSearch data periodically in MongoDB

### ISSUE THREAD

**Issue by bajiat** [apinf/platform#3072]
# User story
As an API owner, I want the dashboard to be performant for an API with large number of calls.

# Description
To make the dashboard views more performant, data from ElasticSearch for one API should be stored periodically in Mongo DB. Any historic data should be available per day. Data for current day could be stored every 10 mins. 

Storing the ES data in MongoDB also makes building the Flow API more straightforward.

To be considered: what is the smallest timeframe the API owner can drill-down to? 5 minutes? Is that true for today / last 7 days only? What about older records?

**Comment by marla-singer** [comment]
# Possible changes in UI
1. Change option of date range picker "Last 24 hours" to "Today". The charts will display data from midnight to current hour.

1. Change UI of Errors statistic table:
- Instead of calls count use relation of success and unsuccess calls
- Rethink about aggregation of one minute. The possible solution is to get last 6-10 records

3. Rethink about chart Unique users API. With pre-aggregated data we would have data for charts per day but not for a total number of a unique user. It would be a high calculated operation and would be better to display Average of unique users number per week

@55 Need your thoughts about these points. Do you agree or disagree? How can we improve table "Errors statistic"?

**Comment by bajiat** [comment]
@marla-singer: I created the issue #3064 for @55 earlier

**Comment by marla-singer** [comment]
> Change option of date range picker "Last 24 hours" to "Today". The charts will display data from midnight to current hour.

@bajiat What about this point?

**Comment by bajiat** [comment]
@marla-singer You are correct, the point about changing "last 24 hours" to "today" is missing

**Comment by Nazarah** [comment]
@marla-singer would you like to take this issue? if so, please estimate.

**Comment by marla-singer** [comment]
@Nazarah I strong recommend to not start this task before #3064 will not resolve. Because the questions about Errors table and total number of Unique users still haven't done and this point has stopped.

**Comment by marla-singer** [comment]
But I think I can start with other charts maybe during my work these items will be resolved or discussed.

> Please discuss with @anarva as he made some solution code related to this.

@anarva Can you please provide links to your changes and related task that you were working on?

**Comment by anarva** [comment]
@marla-singer  I will provide this by the end of business today. Still working on it.
