### ISSUE TITLE
Staging: shows empty page in IE and Edge browsers

### ISSUE THREAD

**Issue by saralavanip** [apinf/platform#3091]
# Steps 
1.Visit https://staging.apinf.io  v 0.51.0  

# Findings  
Shows empty page  

# Operating system   
-  Windows 10  v 1511  
-  Windows 10 v 1703   

# Browsers 
-  Internet Explorer  11  
-  Edge   v 25.10586.672.0

**Comment by bajiat** [comment]
@saralavanip Can you reproduce the error again, go to console and copy-paste what is shown on console? This is potentially related to another error. See: #3088.

**Comment by anarva** [comment]
Could not reproduce with Firefox v.56 or Chrome v.61 on Linux.

**Comment by saralavanip** [comment]
@bajiat , please find the console error message in IE browser screenshot below:  

"SCRIPT5007: Array.prototype.toString: 'this' is null or undefined
bundle.js (104,24987)"    

Screenshot: 

![ie_console_error_message](https://user-images.githubusercontent.com/13309358/32365077-fd01c110-c080-11e7-8e0b-ea2e6b197c57.png)

**Comment by bajiat** [comment]
I was able to reproduce the empty page problem in IE v. 11.674.15063. Did not get any console error, though.

**Comment by matleppa** [comment]
I also was able to reproduce it. IE 11.674.15063.0. 
With console error.

![Staging_error_2017-11-03.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46db809b248b8daeb0ecad51ab4fcfc67917703e7855ee7b23c7af6aaf50740b0a0c0abe4b4a5a41fefadb7ea2e23c76de5909e4d46e5f74903c16fabf870da313f871d51bdaebe5c01982fa3737e68c854e3b1e0c1f89fd583ca59c4dc04abb.PNG)

**Comment by bajiat** [comment]
Same thing for apinf.io in IE: Empty page, zero console errors.

**Comment by bajiat** [comment]
Not able to reproduce in Edge.

Microsoft Edge 40.15063.674.0
Microsoft EdgeHTML 15.15063

**Comment by preriasusi** [comment]
Windows 10 + Firefox: 
<img width="751" alt="apinf io" src="https://user-images.githubusercontent.com/7766712/32373263-1e8441b2-c0a1-11e7-9a7f-897d0ca7f308.png">

**Comment by matleppa** [comment]
@preriasusi also found this API in API catalog (apinf.io).
It seems, that because the name of API is in Chinese (or Japanese), the generation of slug has failed, thus the link being only https://apinf.io/apis

I wonder, whether these have some connection, because the error message was 
Array.prototype.toString: 'this' is null or undefined

![production_error_2017-11-03.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46f88695279780bd86e6b17ca14fe29b3b7975237853ee7a21c8b37bfd0e39111d0014f9121c4d4eeefc8c29a5e46974de5c0db9d46f5671c53d11fab98549b804a83c990dd4e8e8d51199a26867f5819d4e3914041d89f65a34a49b42ca5af349f300.PNG)

But what about error  staging?

**Comment by matleppa** [comment]
Now I was able to reproduce the error in localhost.

IE 11.674.15063.0


92 errors.
![IE_empty_page.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46c1b1a5268f93bd96d6af42a358b2d86b56357c2301a03f32dfa17dea1028030a5b1aac470c5a46f5fc8a2ba6e03d77dc5b0effcd7f1d2598694ef1e1c84afd13b0328a478fb7b98b4cc0ee3f27e38287493a0c48.PNG)

**Comment by matleppa** [comment]
In release 0.49.0 there are no errors.

**Comment by Nazarah** [comment]
Suggestion 1: update meteor to 1.6 to release 51 to see if the problem goes away.
Suggestion 2: isolate this problem from development branch and make a release 51 if the problem takes too much time to solve

**Comment by matleppa** [comment]
Researching suggestion 1. (update Meteor 1.6 to release 0.51.0)
- checked out release 0.51.0 (errors)
- upgrading Meteor to 1.6 (in Windows)
  - requires new installer chocolatey
    - installed (slowly, success on second time)
  - installing Meteor
    - recommends installing a new version of Mongo database engine
    - slowly, lots of error -4048 (operation not permitted)
    - going on...

**Comment by matleppa** [comment]
2017-11-14

Cont'd

Reinstalling ShareJS: meteor add mizzao:sharejs, meteor add  mizzao:sharejs-ace
- stilll: ReferenceError: ShareJS is not defined

While installation (in this case $ meteor npm install --save bcrypt), an error message "error MSB4019: The imported pr
oject "C:\Microsoft.Cpp.Default.props" was not found"

**Comment by matleppa** [comment]
2017-11-16

### Continuing again
- checkout for release 0.51.0
- Meteor upgrade to 1.6

**Comment by matleppa** [comment]
2017-11-17

### What about downgrading Meteor version?
$ meteor --release 1.4.4.3

**Comment by matleppa** [comment]
2017-11-21

### Struggle agains Meteor continues
- Could not get Meteor to start yesterday. Perhaps the folder path has become too deep while unistalling and reinstalling?

**Comment by matleppa** [comment]
2017-11-22

### checking, whether a working combination can be found

- because nightly seems not to suffer from this problem, is it possible, that with latest content of develop branch may contain some fixes, which accidentally help here also?

- Meteor 1.5.2 + branch /develop
  - suggests installing some packages: meteor npm install --save chart.js json2csv select2 select2-bootstrap-theme
 - installed and a new Meteor start
   - same outcome: SCRIPT5007: Array.prototype.toString: 'this' is null or undefined

- trying to downgrade Meteor to 1.4.4.2
  -

**Comment by anarva** [comment]
An imported swagger UI bundle JavaScript file which has been minified caused the problem - the compressed product was not compatible with IE. I have submitted a code fix for review.
