### ISSUE TITLE
[ API Profile ] After updating value of API it redirects to API catalog

### ISSUE THREAD

**Issue by marla-singer** [apinf/platform#3139]
### Steps
1. Create an API or go to existing API
2. Navigate to Settings tab
3. Change Lifecycle status, description or URL value (but not Name parameter)
4. Click on the button "Save"

### Expected result
- API profile information is updated and the API Profile page is still open
- No errors

### Actual result
- Error on the server side
```
Exception from sub apiComposite id PkGJF89NkXef6kiLa Error: Match error: Expected string, got null
  at exports.check (packages/check.js:55:15)
  at [object Object].<anonymous> (apinf_packages/apis/collection/server/publications.js:57:3)
```
- Redirect to API Catalog

**Comment by saransh-dev** [comment]
Hi @marla-singer ,

As i found the issue, `this.updateDoc.$set.slug;` gets `undefine` when we upate api except api name inside autoform file in `apis/profile/settings/details/`.

And because of `autorun` inside onCreated in view.js in `apis/profile/`. Before route, `FlowRouter.getParam('slug')` gets `null`.

So, we can check slug before using inside onCreated.

Please advise.

**Comment by saransh-dev** [comment]
Hi @marla-singer ,

As i found the issue, `this.updateDoc.$set.slug;` gets `undefine` when we upate api except api name inside autoform file in `apis/profile/settings/details/`.

And because of `autorun` inside onCreated in view.js in `apis/profile/`. Before route, `FlowRouter.getParam('slug')` gets `null`.

So, we can check slug before using inside onCreated.

Please advise.

**Comment by marla-singer** [comment]
1. In the file `apis/profile/settings/details/` remove `else` branch - don't redirect to Catalog

> So, we can check slug before using inside onCreated.

2. Yes, go ahead
