### ISSUE TITLE
Landing always on the page 1 in API katalog.

### ISSUE THREAD

**Issue by Laura-Sampo** [apinf/platform#3169]

**Comment by preriasusi** [comment]
@55 Is this something that will be re-impelmented soon or should this be taken as own issue to fix?

**Comment by 55** [comment]
it's certainly a bug, we need to fix it

**Comment by krashna-deligence** [comment]
Hi @55 back button working according to history. When we press back button it goes to `/api` , because in history , previous routing is /api .

**Comment by Nazarah** [comment]
@kyyberi Can you please explain the necessity of configurable transparency of topmenu?
Right now we have the option to change the transparency of cover photo overlay.
I apprehend that if we allow having transparency control for top menu as well, there might be situations when the contrast between topmenu items and coverphoto become blurry and would be difficult to see the menu items because of the image.
