### ISSUE TITLE
Migration 12 does not remove old social media links

### ISSUE THREAD

**Issue by matleppa** [apinf/platform#3333]
### Description

In Branding DB the Social media link structure was changed with PR 3222.

Previously social media links were stored into an array.
After change there is a social media object containing named parameters for links.

Migration fills new structure by converting old links.

### Problem
Migration is not removing old array of social media links after conversion, thus it remains.
Unnecessary old structure of social media links should be removed.

**Comment by marla-singer** [comment]
> Migration is not removing old array of social media links after conversion, thus it remains.
Unnecessary old structure of social media links should be removed.

Can't agree on this point. During migration, it doesn't recommend to remove old data because it needs to keep persistent, consistent data and keep a possibility to roll back between releases, for instance

@apinf/developers Please add comment as well

**Comment by matleppa** [comment]
Closed as unnecessary.
