### ISSUE TITLE
Dashboard UX testing

### ISSUE THREAD

**Issue by 55** [apinf/platform#3418]
Test our dashboard pages and make a list of possible bugs, improvements.

**Comment by Nazarah** [comment]
Environment: https://nightly.apinf.io
OS: Windows 10
Browsers: Chrome (Latest), Microsoft Edge 41.16299.248.0

**Comment by Nazarah** [comment]
**Known Issues:**
1. Charts in "Last 24 hours" timeline should have x-axis divide into hours instead of showing a single unit.
2. (last 24 hours & last 7 days), API request overview shows fraction of one single requests in Y-axis (e.g. 0.2,0.4,0.6,0.8,1.0). One single request shouldn't be broken down into fraction as request is a whole number.

**Comment by Nazarah** [comment]
Improvement Suggestions:
1. Using line charts instead of bars to show changes in trends in KPIs for overview charts.
2. When   going into analytics view  from   Dashboard, browser tab shows it with name "Blank Page". This should   be named as something: "Analytics - <API Name>"
3. When an API is connected to a proxy and calls are made to it, the API appears in   dashboard view after 30 minutes. This is a big UX problem and can act as an   obstacle during demonstration. Optimize this time s.t. APIs appear in DB   within no more than 5 minutes.
4. When   a new API is newly added, no comparison values should appear for any KPIs for   any selected time period.
5.   Should we consider keeping KPI comparison for only last 24 hours? This would   make calculation easier. Beside we    need a bit more research to think about how to show KPI comparison for   last 7 days and last 28 days.
6. More   details about unique user is needed. Unique user is counted if users use API   keys. But this information is missing
7. For a   newly added API, should we consider showing last 7 days and last 28 days   options only if the API is that much older? (Alt: Date picker?)
8. Do we   need to consider comparison rate that is above 100%?
9.   Keeping a separate controller, UI to make comparison? The comparison could be   made within a customized time inter val (starting point: Connecting an API to   proxy and calling it, End point: current date) This might make the   calculation easier.  Comparison can   show different metrics as numbers. Also API calls and type of responses can   be shown as achart.  The time selection   should be date basis
10.
http://recordit.co/3BGhmw35E7
In the API request timeline, is it needed to show API response plot (for 2xx, 3xx, 4xx and 5xx) if the number of respond for a specific category is 0? the above video was taken for Last 7 days time period.

**Comment by Nazarah** [comment]
**Improvement Suggestions:**

13. Should we consider showing all APIs in a single ist instead of diving them to my APIs, APIs I manage and Other APIs (admin role)? If we have a filtering option that can show APIs in the dashboard if I filter it with an organization name (e.g. considering API is added in the dashboard.) then we don't need to keeps separators like above. This is also better in the sense, large numbers APIs under one category (e.g.) will not hold up the most place in the page.

14. Can we also somehow incorporate showing APIs per proxy within filtering option? I got confused when I returned to the Dashboard after making some calls and the the API was not appearing in the list. (The PAI was connected to a proxy via API profile). I had to manually select a proxy to make the added API appear in the list.
