### ISSUE TITLE
Analytics - improve 24 h graphs to show hourly data

### ISSUE THREAD

**Issue by preriasusi** [apinf/platform#3431]
Currently on APInf dashboard it's possible to choose "Last 24 hours". And it will show data of about today with one bar.

Task: Replace "Last 24 hours" option with two options: "Today" and "Yesterday".

"Today" shall show data per hour from midnight until the end of today. And it shall have one bar per **hour**.

"Yesterday" shall show the data from yesterday from midnight to midnight, and it shall render one bar per every **hour**.

**Comment by preriasusi** [comment]
@marla-singer All ok with this one?

**Comment by marla-singer** [comment]
@preriasusi Yeah, seems fine

**Comment by matleppa** [comment]
The X-axis title of charts "API Request Timeline" and "API Response time chart" 
should reflect the selected period.

When "Last 7 days" or "Last 28 days" are selected, the title should be "Days".
When "Today" or "Yesterday" is selected, the title should be "Times" or "Times of day".

![3442_28_timeline_title.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58808c6c07891b1a009b4ae0/125516c66e82c728ace21e0d46bbc0ce71bdd1f1b0fdb64ea151f99a2c79337a3d08a6693cc7f33ab0487e021b4d44be445d5d47aeac8d7fa6b0687588550eeed16d0975c16b16a9aa9e0dfd50e474d412dcfce9c85ecafa3c2ced8a8a4d3d1a011c88ff5532a9995985.PNG)

**Comment by matleppa** [comment]
Explanatory texts below charts in comparison

I assume, that when "Yesterday" is selected, the comparison is done such a way, that if there were e.g. 80 requests on day before yesterday and 40 requests on yesterday, the text begins "50% less than..."

So when "Yesterday" is selected, the text should be "50% less than previous day" instead of "50% less than yesterday" as the text states now.
Accordingly, when "Last 7 days" or "Last 24 days" is selected, the text should be "50% less than previous 7 days" or "50% less than previous 24 days"

@marla-singer What do you think?

![3442_yesterday_compare_texts](https://user-images.githubusercontent.com/23265155/38613732-7d1017aa-3d93-11e8-9a8d-b13639e8a94b.PNG)

**Comment by matleppa** [comment]
On detail page, when the "Today" is selected, the text "Last update was XX minutes ago" needs not to be shown.


![3442_data_today_last_update](https://user-images.githubusercontent.com/23265155/38615879-deb9aed8-3d9a-11e8-9f80-631633096e6c.PNG)

**Comment by marla-singer** [comment]
> When "Today" or "Yesterday" is selected, the title should be "Times" or "Times of day".
(Later addition) In this case "Hours" might be most suitable title.

@matleppa I made "Hours" title

**Comment by marla-singer** [comment]
> On detail page, when the "Today" is selected, the text "Last update was XX minutes ago" needs not to be shown.

Can't agree with this point. The cron task is still running every 30 mins to fetch data from ES and store it in MongoDB.

**Comment by matleppa** [comment]
> On detail page, when the "Today" is selected, the text "Last update was XX minutes ago" needs not to be shown.
Can't agree with this point. The cron task is still running every 30 mins to fetch data from ES and store it in MongoDB.

OK, now I see your point and why the update text was removed from Yesterday.

**Comment by marla-singer** [comment]
> OK, now I see your point and why the update text was removed from Yesterday.

Yep, exactly
