### ISSUE TITLE
Documentation tab under API is blank after platform update to version 0.54.0

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3491]
After updating to version 0.54.0 migration fails and documentation tab is blank. -> it broken.

**Comment by ilarimikkonen** [comment]
![itbroken1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46e18098318d88ac81b8fd0fe64de29b234324676b5ee17e25d7b02aba167f51590b4bae485d5c44fcaf882cf0b13962964e49bc8f3900299f7744eeaa880dbe06b0218e4d82b4b8824bc6ef342de399c2.PNG)

**Comment by ilarimikkonen** [comment]
![Screenshot_20180525-170816.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc791375266455f47b28d4b56af3006b1300051bff054a5556f9fc8b28f4e338248a5a5fe8d3645a77c63d47adbfd418ba13a632c91edbe2e3d7158abd7f37ed998e46341f001a8efd593da89b4ac05dff59ac.png)
![Clipboard - 25. toukokuuta 2018, klo 12.59.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d608343220330011111451/125516c66e82c728ace21e0d46cb989333808ca89dedff0ee40fa5da69522866220ba83e6591e268ed122a59434f15f01e485e46e2fc8039baa47c32d5065ebe957f5566c33813afead71beb01bc748e4d8cb3bf8a4c96e93a73e08e9d532c5c5446dda0006ceacc09da52e44ae84754a1113161e27e3e7e469c18763e26.png)

**Comment by ilarimikkonen** [comment]
migration is failing
So it locks and stops. Restarting won't fix this one

**Comment by matleppa** [comment]
It seems, that migration step 3 is the culprit here.
#### Cause 
Previously the documentation link has been in Apis and with this migration it is moved to ApiDocs, to field otherUrl. 
At the time the type of otherUrl has been string.
However, later the type of field otherUrl is changed to array (related migration is step 14), thus causing step 3 to fail when migration target ApiDocs is on newer level.

#### Solution alternatives
- change the step 3 to update field otherUrl as type array
  - in case it is sure, that there will be no update toward ApiDocs level lower than step 14
- in case the release level is above step 3 (no documentation in Apis), try to continue migration
  - open lock
  - set migration version to 3 (to set migration to continue with step 4)

**Comment by preriasusi** [comment]
@phanimahesh @ilarimikkonen Is this still open? Any fixes?

**Comment by phanimahesh** [comment]
We have manually skipped the migration 3 to resolve this on tampere3. A proper fix needs an update to the migration code

**Comment by ilarimikkonen** [comment]
alternatively, can maybe change step 3 so that nothing is done. In this case you need to check that there is no documentation data in Apis db
