### ISSUE TITLE
Subrequest rules for CORS preflight requests

### ISSUE THREAD

**Issue by phanimahesh** [apinf/platform#3498]
## Current Behaviour
If an api has authentication enabled, preflight check fails since browsers always make a plain request without `x-api-key` credentials for preflight.

## Intended Behaviour
CORS preflight requests must not fail if an api is expected to be used cross-origin.

## Proposal
1. Add a UI element (checkbox/radio?) to api settings to indicate if CORS should be enabled for the api.
2. If CORS is enabled by api owner
    1. Add a subrequest rule to api umbrella exempting `OPTIONS` requests from authentication.
    2. Add `Access-Control-Allow-Headers: x-api-key` to response headers for `OPTIONS`.

## Other considerations
This expects the backend api servers to understand and respond to `OPTIONS` requests in a CORS-compliant manner. i.e; the response should contain headers `Access-Control-Allow-Origin`, and if necessary, other `A-C-A-` family of headers.

### Relevant issues
 - https://github.com/apinf/platform/issues/3402
 - https://github.com/apinf/platform/issues/2696
 - https://github.com/apinf/platform/issues/2604

https://github.com/apinf/platform/issues/2604#issuecomment-334092528 is a quick read on CORS protocol.
https://github.com/apinf/platform/issues/2696#issuecomment-340400284 proposes this solution roughly, and explains why it'll work.

**Comment by matleppa** [comment]
Is there possibility to configure apiUmbrella such a way, that a header (here X-Api-Key) is *appended* into A-C-A-H in OPTIONS response? 

I wonder if we should try to have a correction in Api Umbrella general functionality rather than to try to fix it with configuration patches API by API.
apiUmbrella (globally)
- never to require x-api-key header within OPTIONS request
- always append x-api-key into A-C-A-H in OPTIONS response from API, in case it was in OPTIONS A-C-R-H, but not in original response from API

**Comment by phanimahesh** [comment]
A-C-A-H is allowed to appear multiple times. We can configure umbrella to add the header unconditionally. If it is already sent by backend, the header appears twice in response and is interpreted correctly by all spec-conforming clients.

Fixing it at api umbrella level will take more effort comparatively, hence our interest in fixing it at our level.

**Comment by preriasusi** [comment]
No append in Umbrella for append response headers in API Umbrella. Closing this now.
