### ISSUE TITLE
unable to change API port in proxy settings

### ISSUE THREAD

**Issue by ilarimikkonen** [apinf/platform#3500]
how to repro: add api. app proxy settings. change API port. hit save & publish.

expected: port change takes effect
actual: port stays same (443) or /and internal server error is thrown.

tested with : https://nightly.apinf.io/apis/bacon#api-proxy

**Comment by matleppa** [comment]
In the code base the value of API port is handled such a way, that the value of port is gottem from a helper, which sets to the port one of two values depending on the protocol of URL (HTTP / HTTPS).


There are no comments to indicate, if this is intentional or whether the goal might have been only to set default value if nothing is given.

api_umbrella.html

      {{> afFieldInput
        name="apiUmbrella.servers.0.port"
        value=apiPortHelper
        class="form-control"
        aria-describedby="api-port-field-label"
        id="api-port-field"
      }}


api_umbrella.js

    apiPortHelper () {
     // Get API information
     const api = this.api; 
 
     // Construct URL object for API URL
     const apiUrl = new URI(api.url);
 
     // Return the API URL protocol
     const protocol = apiUrl.protocol();
 
     // Common default ports for HTTP/HTTPS
     if (protocol === 'https') {
       return 443;
     }
 
     if (protocol === 'http') {
       return 80;
     }

     return '';
     },
